###0. Import Necessary Dependencies for Datasets and Experiments

In [1]:
!pip install -qqq arize arize-phoenix certifi urllib3

In [2]:
import os, certifi
CA = certifi.where()

os.environ["SSL_CERT_FILE"] = CA
os.environ["REQUESTS_CA_BUNDLE"] = CA
os.environ["CURL_CA_BUNDLE"] = CA

print("Using CA:", CA)

Using CA: /Users/sean/projects/notebooks/.venv/lib/python3.13/site-packages/certifi/cacert.pem

In [3]:
from typing import Any, Dict
from arize import ArizeClient
from openai import OpenAI
import pandas as pd
from dotenv import load_dotenv

import os
import requests

load_dotenv()

API_KEY = os.getenv("ARIZE_API_KEY")
SPACE_ID = os.getenv("ARIZE_SPACE_ID")

In [4]:
client = ArizeClient(api_key=API_KEY, request_verify=False)

In [5]:
examples = client.datasets.list_examples(
    dataset="cnn_dailymail_small",
    space=SPACE_ID,)

  arize.pre_releases | WARNING | [BETA] datasets.list_examples is a beta API in Arize SDK v8.20.0 and may change without notice. If you experience unexpected failures, please upgrade to the most recent version of the package.

In [6]:
examples

DatasetsExamplesList200Response(examples=[DatasetExample(id='02f0f515-7050-4589-ad0e-2b15efb13202', created_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), additional_properties={'article': 'WASHINGTON (CNN) -- Vice President Dick Cheney will serve as acting president briefly Saturday while President Bush is anesthetized for a routine colonoscopy, White House spokesman Tony Snow said Friday. Bush is scheduled to have the medical procedure, expected to take about 2 1/2 hours, at the presidential retreat at Camp David, Maryland, Snow said. Bush\'s last colonoscopy was in June 2002, and no abnormalities were found, Snow said. The president\'s doctor had recommended a repeat procedure in about five years. The procedure will be supervised by Dr. Richard Tubb and conducted by a multidisciplinary team from the National Naval Medical Center in Bethesda, Maryland, Snow said. A colonoscopy is the most sensitive test for colon cancer, rectal cancer and polyps, small clumps of cells that can become cancerous, according to the Mayo Clinic. Small polyps may be removed during the procedure. Snow said that was the case when Bush had colonoscopies before becoming president. Snow himself is undergoing chemotherapy for cancer that began in his colon and spread to his liver. Snow told reporters he had a chemo session scheduled later Friday.  Watch Snow talk about Bush\'s procedure and his own colon cancer » . "The president wants to encourage everybody to use surveillance," Snow said. The American Cancer Society recommends that people without high-risk factors or symptoms begin getting screened for signs of colorectal cancer at age 50. E-mail to a friend .', 'highlights': "President Bush will have a routine colonoscopy Saturday .\nWhile he's anesthetized, his powers will be transferred to the vice president .\nBush had last colonoscopy in 2002, which found no problems ."}), DatasetExample(id='07e3623e-28ab-4a02-af85-da20432e58bc', created_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), additional_properties={'article': "(CNN) -- This week MME speaks to the man charged with boosting growth in the Kingdom of Bahrain: Sheikh Mohammed bin Isa Al Khalifa. Sheikh Mohammed is concerned the nuclear dispute with Iran  is deterring potential investors . As chief executive of the Economic Development Board, one of Sheikh Mohammed's main tasks is to ensure Bahrain stays ahead of its competitors. The government's pushing ahead with economic reforms to reduce the Kingdom's dependence on oil. But with crude prices near $100 a barrel, John Defterios asked whether the appetite for change had diminished. SM: The reforms are being done for aspirational reasons rather than necessity, so we are trying to enter the post-oil area because we want to. And therefore, because of this aspirational aspect, trying to get to as opposed to people pushing us somewhere we don't want to go. JD: How do you redefine Bahrain's role? Traditionally it's been a financial center, but you have Qatar, Saudi Arabia, Dubai even Abu Dhabi emerging in financial services. How you redefine it to sustain a lead? SM: The rising tide lifts a lot of places and as the region is booming and growing, financial services are growing throughout the region. Bahrain's strengths have been and will continue to be its human capital, the people that have led the financial sector and the long standing regulations that have been established in Bahrain. JD: Strategically and a geopolitical question here: the Crown Prince came out and declared what Iran's intentions really are -- in his view -- for a nuclear policy, and called for greater diplomacy right ahead of a visit by the President of Iran to the country. What's the motivation here? SM: We feel that the distraction caused by the Iranian nuclear issue is holding investment back in the region as a whole, and increasing the security threat of the region. Nobody is debating the right to peaceful nuclear power, but we all have that need and we all need a peaceful resolution to this. JD: Historically, Iran has even made claims against Bahrain, what do you do now moving forward now? Do you bring Russia, China, the United States and the European Union closer together, in terms of where we should be going in the future? SM: We've resolved our historical issue with Iran, and we are well beyond that, but going forward... This is such a important issue affecting security worldwide, that we feel it is important and at a level high enough that we need all powers involved because it does affect everybody. JD: Can the GCC (Gulf Cooperation Council) become much tighter as an organization to have a voice in that process; as opposed to speaking from the sidelines and hoping that the major powers move forward? SM: Absolutely, I mean, the GCC is speaking with a unified voice. The Kingdom of Saudi Arabia came out with a proposal for providing nuclear fuel from an independent authority; this was completely backed from the GCC. We are all moving forward and are willing to play a beneficial role to resolve this issue. Meet the Sheikh: . Sheikh Mohammed bin Isa Al Khalifa is chief executive of the Economic Development Board, the organization responsible for stimulating and supporting growth of the Bahraini economy. He was appointed in June 2005, following 10 years working directly for His Highness Sheikh Salman bin Hamad Al Khalifa, Crown Prince, Commander-in-Chief of the Bahrain Defense Force and Chairman of the Economic Development Board. From 1995 to 1999, he was director of the Crown Prince's office. In 1999, he was appointed head of the court and also deputy head of the Crown Prince's International Scholarship Program. During this time, Sheikh Mohammed was heavily involved with the Crown Prince's initiatives to liberalize the telecommunications sector and with labor market and economic reforms. A keen motor sports enthusiast, Sheikh Mohammed was deputy board chairman of the Bahrain International Circuit and is a former vice president of the Bahrain Motor Club, now known as the Bahrain Motor Federation. Sheikh Mohammed, who is married with two sons and one daughter, was born on April 14, 1969. In 1992, he received a bachelor's degree in economic theory from the American University, Washington DC. Two years later, he received a post-graduate diploma in business studies from the London School of Economics. (source: Bahrain Economic Development Board) E-mail to a friend .", 'highlights': 'Sheikh Mohammed bin Isa Al Khalifa steers Bahrain\'s economic growth .\nSays Bahrain\'s strength is its "human capital" in the finance sector .\nCalls on world to unite to resolve nuclear dispute with Iran .'}), DatasetExample(id='0bbcf3ed-2a7c-4ed0-ba8c-9c96bc036b00', created_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), additional_properties={'article': 'LAS VEGAS, Nevada (CNN)  -- Former football star O.J. Simpson will be held without bail after his arrest on robbery and assault charges, police announced late Sunday. Police released this mug shot of O.J. Simpson after his arrest. Simpson is accused of having directed several other men in an alleged armed robbery of sports memorabilia in a room at a Las Vegas hotel room. Las Vegas authorities said they have no information leading them to believe Simpson was carrying a firearm during the alleged incident at the Palace Station Hotel and Casino. Police said Simpson and other men burst into the room and walked out with the memorabilia, including some that was unrelated to Simpson, police said. "We don\'t believe that anyone was roughed up, but there were firearms involved," Lt. Clint Nichols told reporters. Nichols said the firearms were pointed at the victims. A reporter asked Nichols: Was "O.J. was the boss in that room?" Nichols responded, "That is what we believe, yes."  Watch Simpson transferred Sunday in handcuffs » . The alleged victims were identified as Bruce Fromong, a sports memorabilia collector who described the incident as "a home invasion-type robbery," and Alfred Beardsley, who has been quoted by celebrity Web site TMZ.com as saying that Simpson later apologized to him and told him he regretted the incident. Acting on a tip, police met over the weekend at McCarran International Airport with 46-year-old Walter Alexander, of Mesa, Arizona, who told them about the alleged robbery and validated the tipster\'s information, Capt. James Dillon told reporters. Alexander was arrested Saturday night on two counts of robbery with a deadly weapon, two counts of assault with a deadly weapon, conspiracy to commit robbery and burglary with a deadly weapon. He was released on his own recognizance and returned to Mesa either Saturday night or early Sunday morning, Dillon said. In addition, investigators are seeking four other men they believe accompanied Simpson into the hotel room, Nichols said. Nichols said, "There is a social relationship between the individuals that we identified and O.J. Simpson." Though Simpson is not accused of having brandished a gun himself, two firearms that police said were used were recovered early Sunday in one of three searches. Investigators would would not divulge where the weapons were found. Nichols dismissed an initial report that the men may have been off-duty police. "There is no truth to that whatsoever," he said. "That came as a result of some language that was used when the individuals burst into the room that led our victims to believe that they may have been police." Simpson, 60, has acknowledged taking some items that belonged to him, but he has denied that any weapons were involved. "Whether the property belonged to Mr. Simpson or not is still in debate," Nichols said. "We are still in the process of sorting that out." Nichols also said that some of the property taken had Simpson\'s signature. But "there was some other property taken as well," he said. "I believe there were some Joe Montana cleats and some signed baseballs and other stuff." The latest charges against Simpson mean he faces the prospect of another prosecution, more than a decade after the June 1994 stabbing deaths of his ex-wife, Nicole Brown Simpson, and Ron Goldman. Simpson was acquitted of murder the following year. The trial riveted much of the United States. But in 1997, a jury found him liable for the deaths in a civil case brought by the Goldman family. Simpson was ordered to pay the families a total of $33.5 million for the deaths . Goldman had gone to Nicole Simpson\'s Los Angeles home to return a pair of glasses the day of the slayings. Goldman\'s sister, Kim Goldman, said she wasn\'t surprised by the robbery allegations, since Simpson "thinks he can do no wrong." "He\'s capable of stabbing people to death, so I think robbery is nothing surprising," she said. "Normal, logical, civil-minded, law-abiding people don\'t storm a room with guns demanding stuff back." Fromong had testified on Simpson\'s behalf in the civil case, telling the court that prices for Simpson memorabilia had dropped substantially since the 1995 verdict. His testimony was part of the defense\'s contention that Simpson could not afford to pay the Goldmans. Simpson recently wrote a book originally titled "If I Did It" and had planned to publish it himself, but a public outcry led to the cancellation of his book deal. A bankruptcy judge subsequently awarded the Goldmans the rights to the book in light of their inability to collect the wrongful death award. The Goldmans retitled the book, "If I Did It: Confessions of the Killer." That book just hit bookstores. E-mail to a friend . CNN\'s Ted Rowlands contributed to this report.', 'highlights': 'No bail for ex-NFL star accused of directing men in alleged armed robbery .\nSimpson faces charges of robbery, assault, burglary and conspiracy .\nAlleged robbery involved sports-related items, police say .\nSimpson arrested Sunday in Las Vegas, but he says items were his .'}), DatasetExample(id='14530878-20b1-4117-a0b3-3e0442d7806d', created_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), additional_properties={'article': 'BAGHDAD, Iraq (CNN) -- None of the 1,000-plus Iraqi detainees freed in recent weeks have broken a pledge not to return to the insurgency, according to the Marine general who oversees the U.S. detention centers in Iraq. A U.S. military panel reviews a detainee\'s case at Camp Cropper near Baghdad. Speaking in Arabic, Maj. Gen. Doug Stone on Wednesday reassured Iraqis about how the 25,000 detainees -- mostly Sunnis -- are treated after being taken into custody on suspicion of involvement in the insurgency. Stone described the detention system as "open and transparent," saying it makes the detainees better citizens and helps break the cycle of violence and poverty in the country. Stone said detainees get free medical care equal to what he gets as a general, food and water made to Islamic standards, educational opportunities, jobs skills and contact with families. The U.S. detention centers -- at Camp Bucca near the southern port city of Basra and in Camp Cropper near Baghdad -- are political sore points for Sunnis, who make up 83 percent of the detainees held. The main Sunni political coalition -- the Iraqi Accord Front -- cited the centers as one reason for quitting the government during the summer. Last month, the U.S.-led coalition launched Operation Lion\'s Paw in which between 50 and 70 detainees would be released daily during the Islamic holy month of Ramadan after taking a pledge not to rejoin the insurgency against the Shiite-led government. "This pledge is an Iraqi pledge, a pledge before an Iraqi judge, frequently with a family member present," Stone said. "I am pleased to tell you that in the more 1,000 that have gone through this program and taken the pledge, not one has returned to threaten Iraqi or coalition forces." Stone said the releases would continue at the same pace beyond Ramadan. Stone\'s description seems a far cry from the Abu Ghraib prison operated by the U.S. military in the first years after the invasion. That prison was closed down and razed in the wake of an international scandal over prisoner abuse. "There are no secrets that go on in detention," Stone said. "Our facilities are open to inspection by any agency that we in the federal government believe is credible. These agencies are welcomed because they are windows for the world."  See what life\'s like inside Camp Cropper\'s walls » . By the time of their release, "detainees grow in terms of working in an inter-sectarian environment," he said. Each detainee has a chance to take classes up to a sixth-grade level, and high school classes are being planned, Stone said. About one-third -- or 8,000 -- are in school, with 7,000 having passed the fifth-grade level, he said. The 860 detainees who are 17 or younger are all in school, Stone said. The average stay for a detainee is 300 days, but some have been detained for two years or longer, he said. A review board interviews detainees to decide if they are a threat to security, he said. If they are deemed not to be, they are offered freedom in exchange for taking the pledge. Only 280 detainees are foreigners, mostly from Syria, Egypt, Iran, Sudan and Saudi Arabia, he said. Other developments .', 'highlights': 'More than 1,000 freed detainees reportedly keep pledge not to rejoin insurgency .\nU.S. general tries to reassure Sunnis that detainees face no abuse .\nMore than 80 percent of detainees are Sunnis .\nU.S. airstrike kills 13 suspected terrorists west of Baghdad .'}), DatasetExample(id='1662495f-657a-4531-80e6-448826780fb2', created_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 2, 44, 39, tzinfo=TzInfo(0)), additional_properties={'article': '(LiveWire) -- Voluble Gary Vaynerchuk, 31, the host of "Wine Library TV," an online video show, has been known to lick rocks, suck leather and eat dirt while on camera, all to illustrate the unique properties of wine. "Wine Library TV" host Gary Vaynerchuk discusses four spooky wine varieties for Halloween show. Of a "wild and gamey" red from Rioja, Spain, Vaynerchuk says, "Hit a deer on the road. Throw a bunch of cherries on it. Take out your knife, cut the deer. Bite it. That\'s the flavor profile." That kind of attitude appeals to people who are mystified by the arcane lexicon of traditional wine journals or turned off by what they perceive as elitist barriers. Across the Internet, budding wine geeks are discovering a burgeoning number of Web sites, blogs, bulletin boards and other outlets that preach the gospel of the grape in terms they can understand. About 40,000 Internet viewers  -- many of them 20-somethings -- have a daily appointment with "Wine Library TV." The low-budget video blog is produced five days a week from a nondescript office in the three-level wine retail operation that Vaynerchuk\'s family owns in Springfield, New Jersey. Vaynerchuk has a discerning nose and palate, and he doesn\'t dumb down his subject. Yet he stuffs his patter with sports and pop-culture references -- and the kind of language a Wine Spectator critic would be unlikely to employ. The mission of wine sites like "Wine Library TV," say several of the people behind these new outlets, is to demystify wine (and in some cases, sell it, too). Using the language, attitude and new media that appeal to a young, tech-savvy generation, they advocate trusting one\'s own palate rather than obeying powerful wine critics. Some of the sites also provide opportunities for average wine drinkers to share their opinions. One site, SavorEachGlass.com, declares its dedication to "exploring the spirit of wine for a new generation," with reviews, online journals and essays that explain the finer points of winemaking  -- all with attitude. "The (wine) establishment is about ratings and \'reputation,\'" says the site\'s founder, Tynan Szvetecz, 29. "It\'s about collecting the \'good\' stuff as defined by someone else\'s palate and tastes. That bores a younger generation." "We\'re not afraid to be smartasses," he continues. "We make fun of ourselves, old-world wine makers, new-world wine makers, and anyone else we can get our hands on." In the U.S., interest in wine is exploding. While consumption has leveled out in traditional wine-producing countries such as France, Italy and Spain, especially among young people, it has trended upwards in the U.S. for 15 straight years. The U.S. is projected to overtake No. 2 Italy by the end of 2007, according to the annual report The U.S. Wine Market: Impact Databank Review and Forecast a leading industry trade publication. Many of the new converts to wine are the so-called Millennials, the under-30 age group coveted by beverage marketers and so comfortable online that they\'re also called iGen, or the Internet Generation. One of the wine Web sites targeting a younger demographic is VineSugar.com, which features a blog called "Wine Burps." "We love wine but hate the elitism," writes founder, Ryan O\'Donnell. "After all, it\'s just grape juice." With rants about wine tasting fees, a feature spotlighting "wine hotties" working at California wineries, as well as interactive maps that plot and rate wineries, VineSugar.com leaves little doubt about its target audience. CellarTracker.com, an online wine community, appeals to more established wine collectors. The site provides free software  -- designed by Eric LeVine, a fortuitously named former Microsoft software developer  -- that allows wine enthusiasts to create an online inventory of their wines. The 39,000 users (who count 6 million bottles in their virtual cellars) post revie

In [ ]:
from langchain_core.output_parsers import StrOutputParser
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4.1-2025-04-14", temperature=0.0)
chain = llm | StrOutputParser()

prompt = """You are a helpful assistant that summarizes articles.
Summarize the following article in a concise manner:
{article}
"""

def sample_task(dataset_row) -> str:
    # print("Dataset row:", dataset_row)
    article_text = dataset_row["article"]
    return chain.invoke(prompt.format(article=article_text))

In [11]:
from phoenix.evals import llm_classify, OpenAIModel
from arize.experiments import EvaluationResult
import pandas as pd

eval_prompt_template = """
You are comparing the summary text and it's original document and trying to determine if the summary is good. Here is the data:
    [BEGIN DATA]
    ************
    [Summary]: {output}
    ************
    [Original Document]: {input}
    [END DATA]

Compare the Summary above to the Original Document and determine if the Summary is comprehensive, concise, coherent, and independent relative to the Original Document. Your response must be a single word, either "good" or "bad", and should not contain any text or characters aside from that. "bad" means that the Summary is not comprehensive, concise, coherent, and independent relative to the Original Document. "good" means the Summary is comprehensive, concise, coherent, and independent relative to the Original Document.
"""

def summary_eval(output, dataset_row):
    eval_df = llm_classify(
        dataframe=pd.DataFrame([{"input": dataset_row["article"], "output": output}]),
        template=eval_prompt_template,
        model=OpenAIModel(model="gpt-4o-mini"),
        rails=["good", "bad"],
        provide_explanation=True,
    )

    # Map the eval df to EvaluationResult
    label = eval_df["label"][0]
    score = 1 if label == "good" else 0
    explanation = eval_df["explanation"][0]

    return EvaluationResult(label=label, score=score, explanation=explanation)

In [17]:
experiment, experiment_df = client.experiments.run(
    name="summary-01",
    dataset="cnn_dailymail_small",
    space=SPACE_ID,
    task=sample_task,
    evaluators=[summary_eval],
    # dry_run=True
)

  arize.experiments.functions | INFO | 🧪 Experiment started.
  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running tasks |██████████| 100/100 (100.0%) | ⏳ 03:53<00:00 |  2.34s/it

  arize.experiments.functions | INFO | ✅ Task runs completed.
Tasks Summary (06/26/26 12:40 PM +0900)
---------------------------------------
   n_examples  n_runs  n_errors
0         100     100         0
  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running experiment evaluations |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s/var/folders/3n/gv0dncrs175g36_29rs1d_r00000gn/T/ipykernel_57168/1836533491.py:18: DeprecationWarning: `dataframe` argument is deprecated; use `data` instead
  eval_df = llm_classify(
🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.89s/it
running experiment evaluations |          | 1/100 (1.0%) | ⏳ 00:02<03:30 |  2.13s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.81s/it
running experiment evaluations |▏         | 2/100 (2.0%) | ⏳ 00:04<03:24 |  2.09s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.52s/it
running experiment evaluations |▎         | 3/100 (3.0%) | ⏳ 00:05<03:09 |  1.95s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it
running experiment evaluations |▍         | 4/100 (4.0%) | ⏳ 00:08<03:23 |  2.12s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.41s/it
running experiment evaluations |▌         | 5/100 (5.0%) | ⏳ 00:10<03:05 |  1.95s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.76s/it
running experiment evaluations |▌         | 6/100 (6.0%) | ⏳ 00:12<03:05 |  1.97s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it
running experiment evaluations |▋         | 7/100 (7.0%) | ⏳ 00:14<03:10 |  2.04s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it
running experiment evaluations |▊         | 8/100 (8.0%) | ⏳ 00:16<03:04 |  2.00s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it
running experiment evaluations |▉         | 9/100 (9.0%) | ⏳ 00:17<02:58 |  1.96s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it
running experiment evaluations |█         | 10/100 (10.0%) | ⏳ 00:19<02:51 |  1.91s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.83s/it
running experiment evaluations |█         | 11/100 (11.0%) | ⏳ 00:21<02:54 |  1.96s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.66s/it
running experiment evaluations |█▏        | 12/100 (12.0%) | ⏳ 00:23<02:51 |  1.95s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.03s/it
running experiment evaluations |█▎        | 13/100 (13.0%) | ⏳ 00:26<02:58 |  2.05s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it
running experiment evaluations |█▍        | 14/100 (14.0%) | ⏳ 00:27<02:53 |  2.02s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.52s/it
running experiment evaluations |█▌        | 15/100 (15.0%) | ⏳ 00:29<02:44 |  1.94s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it
running experiment evaluations |█▌        | 16/100 (16.0%) | ⏳ 00:31<02:40 |  1.92s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.76s/it
running experiment evaluations |█▋        | 17/100 (17.0%) | ⏳ 00:33<02:41 |  1.95s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it
running experiment evaluations |█▊        | 18/100 (18.0%) | ⏳ 00:35<02:38 |  1.93s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it
running experiment evaluations |█▉        | 19/100 (19.0%) | ⏳ 00:37<02:32 |  1.89s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.42s/it
running experiment evaluations |██        | 20/100 (20.0%) | ⏳ 00:38<02:25 |  1.82s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.81s/it
running experiment evaluations |██        | 21/100 (21.0%) | ⏳ 00:41<02:29 |  1.90s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.64s/it
running experiment evaluations |██▏       | 22/100 (22.0%) | ⏳ 00:42<02:27 |  1.90s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it
running experiment evaluations |██▎       | 23/100 (23.0%) | ⏳ 00:44<02:27 |  1.91s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.36s/it
running experiment evaluations |██▍       | 24/100 (24.0%) | ⏳ 00:46<02:18 |  1.82s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.79s/it
running experiment evaluations |██▌       | 25/100 (25.0%) | ⏳ 00:48<02:21 |  1.89s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.14s/it
running experiment evaluations |██▌       | 26/100 (26.0%) | ⏳ 00:50<02:30 |  2.04s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.33s/it
running experiment evaluations |██▋       | 27/100 (27.0%) | ⏳ 00:52<02:18 |  1.90s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it
running experiment evaluations |██▊       | 28/100 (28.0%) | ⏳ 00:54<02:17 |  1.91s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.23s/it
running experiment evaluations |██▉       | 29/100 (29.0%) | ⏳ 00:56<02:27 |  2.08s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it
running experiment evaluations |███       | 30/100 (30.0%) | ⏳ 00:58<02:24 |  2.07s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.41s/it
running experiment evaluations |███       | 31/100 (31.0%) | ⏳ 01:00<02:14 |  1.95s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it
running experiment evaluations |███▏      | 32/100 (32.0%) | ⏳ 01:02<02:13 |  1.96s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it
running experiment evaluations |███▎      | 33/100 (33.0%) | ⏳ 01:05<02:22 |  2.12s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it
running experiment evaluations |███▍      | 34/100 (34.0%) | ⏳ 01:07<02:17 |  2.09s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it
running experiment evaluations |███▌      | 35/100 (35.0%) | ⏳ 01:09<02:15 |  2.09s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.55s/it
running experiment evaluations |███▌      | 36/100 (36.0%) | ⏳ 01:11<02:07 |  2.00s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it
running experiment evaluations |███▋      | 37/100 (37.0%) | ⏳ 01:12<02:05 |  1.99s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it
running experiment evaluations |███▊      | 38/100 (38.0%) | ⏳ 01:15<02:04 |  2.01s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.15s/it
running experiment evaluations |███▉      | 39/100 (39.0%) | ⏳ 01:17<02:09 |  2.13s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.64s/it
running experiment evaluations |████      | 40/100 (40.0%) | ⏳ 01:19<02:03 |  2.05s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.22s/it
running experiment evaluations |████      | 41/100 (41.0%) | ⏳ 01:23<02:43 |  2.78s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.99s/it
running experiment evaluations |████▏     | 42/100 (42.0%) | ⏳ 01:26<02:31 |  2.62s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.12s/it
running experiment evaluations |████▎     | 43/100 (43.0%) | ⏳ 01:28<02:25 |  2.55s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it
running experiment evaluations |████▍     | 44/100 (44.0%) | ⏳ 01:30<02:10 |  2.34s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it
running experiment evaluations |████▌     | 45/100 (45.0%) | ⏳ 01:32<02:10 |  2.37s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.85s/it
running experiment evaluations |████▌     | 46/100 (46.0%) | ⏳ 01:34<02:03 |  2.29s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.15s/it
running experiment evaluations |████▋     | 47/100 (47.0%) | ⏳ 01:37<02:03 |  2.33s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it
running experiment evaluations |████▊     | 48/100 (48.0%) | ⏳ 01:39<02:04 |  2.39s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.98s/it
running experiment evaluations |████▉     | 49/100 (49.0%) | ⏳ 01:42<01:59 |  2.35s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it
running experiment evaluations |█████     | 50/100 (50.0%) | ⏳ 01:43<01:51 |  2.24s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.87s/it
running experiment evaluations |█████     | 51/100 (51.0%) | ⏳ 01:46<01:47 |  2.20s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.77s/it
running experiment evaluations |█████▏    | 52/100 (52.0%) | ⏳ 01:49<01:57 |  2.45s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it
running experiment evaluations |█████▎    | 53/100 (53.0%) | ⏳ 01:50<01:46 |  2.26s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it
running experiment evaluations |█████▍    | 54/100 (54.0%) | ⏳ 01:52<01:39 |  2.16s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it
running experiment evaluations |█████▌    | 55/100 (55.0%) | ⏳ 01:54<01:34 |  2.10s/it🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.
llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

  arize.experiments.functions | INFO | ✅ All evaluators completed.

In [21]:
eval_df = client.experiments.list_runs(experiment=experiment.id, all=True).to_df()
eval_df.head()

,id,example_id,output,result.trace.id,result.trace.timestamp,eval.summary_eval.score,eval.summary_eval.label,eval.summary_eval.explanation,eval.summary_eval.trace.id,eval.summary_eval.trace.timestamp,result
0,EXP_ID_2d60a6,61e8d316-cc2f-4414-ab20-557c2687409b,"**Summary:**\n\nAs Daniel Radcliffe, star of t...",7ae506ea1835144404d2c0946807abd9,1782444975880,1,good,The summary captures the key points of the ori...,6b2fbb968778e5cbab4d9d6f4b4d337a,1782445209881,"**Summary:**\n\nAs Daniel Radcliffe, star of t..."
1,EXP_ID_4c35b5,2c5cc474-c3ab-40f8-af0e-8687c1d5a9ea,**Summary:**\n\nCNN correspondent Soledad O'Br...,4a27ec6ce44609cd09930cd0506c84a2,1782444978470,1,good,The summary effectively captures the main poin...,565160d69c38e66cd88e386937e582c5,1782445212012,**Summary:**\n\nCNN correspondent Soledad O'Br...
2,EXP_ID_9e3d06,5ed19dbb-4650-422d-ade2-baba76909dbd,**Summary:**\n\nWhen the Minneapolis bridge co...,09e33240d1189e653b2107d0170b7b26,1782444980965,1,good,The summary captures the main events and emoti...,32ad3a446a6cf19171ee8103dedb4293,1782445214068,**Summary:**\n\nWhen the Minneapolis bridge co...
3,EXP_ID_be1734,1a21d9bc-9865-4ad7-9b85-86600a3607a3,**Summary:**\n\nPresident Bush had five small ...,36d3a7535357f502a79d398a5954a018,1782444984954,1,good,The summary effectively captures the key point...,a3a3f6df00c13390d28ea1c9fcaf6921,1782445215853,**Summary:**\n\nPresident Bush had five small ...
4,EXP_ID_326413,c9f5975b-7647-4ed4-81cf-89517c261593,**Summary:**\n\nAtlanta Falcons quarterback Mi...,39d34a9125eaabd9b8f4e4e4bdff2cbe,1782444986838,1,good,The summary captures the key points of the ori...,42437440765442780483d265b4a9bfd0,1782445218229,**Summary:**\n\nAtlanta Falcons quarterback Mi...

In [26]:
bad_df = eval_df[eval_df["eval.summary_eval.label"] == "bad"].head(3)
good_df = eval_df[eval_df["eval.summary_eval.label"] == "good"].head(5)
filtered_df = pd.concat([bad_df, good_df])
filtered_df.head(8)

,id,example_id,output,result.trace.id,result.trace.timestamp,eval.summary_eval.score,eval.summary_eval.label,eval.summary_eval.explanation,eval.summary_eval.trace.id,eval.summary_eval.trace.timestamp,result
12,EXP_ID_5a1bfc,aa39bac6-b9fa-436f-b7d3-718fd7170c5c,"**Summary:**\n\nCarlos Alberto, who scored in ...",2de635b2ec94805d68b44d6d62e977e4,1782445011523,0,bad,The summary captures the main points about Car...,98cbaa4294d2deceddd7bd1a3d3a3b6a,1782445233664,"**Summary:**\n\nCarlos Alberto, who scored in ..."
28,EXP_ID_2b1838,29d55a8f-cdbf-4a0b-b3ae-b644458c1d49,"**Summary:**\n\nYoussif, a 5-year-old Iraqi bo...",f5539eac42d03d7bca54d0dc60ba77eb,1782445041907,0,bad,The summary captures the main events of Youssi...,ea9c5f6ee57c33233cea66c2e50a9a8e,1782445264361,"**Summary:**\n\nYoussif, a 5-year-old Iraqi bo..."
93,EXP_ID_48b5f8,6d47b720-cbaf-463c-b122-f1d78d74455c,**Summary:**\n\nPresident Bush vetoed a $600 b...,3c86e074ac20792790346a07f8ed089b,1782445189619,0,bad,The summary captures the main points of Presid...,9480c28c1ef233327122a543a61d1a86,1782445403277,**Summary:**\n\nPresident Bush vetoed a $600 b...
0,EXP_ID_2d60a6,61e8d316-cc2f-4414-ab20-557c2687409b,"**Summary:**\n\nAs Daniel Radcliffe, star of t...",7ae506ea1835144404d2c0946807abd9,1782444975880,1,good,The summary captures the key points of the ori...,6b2fbb968778e5cbab4d9d6f4b4d337a,1782445209881,"**Summary:**\n\nAs Daniel Radcliffe, star of t..."
1,EXP_ID_4c35b5,2c5cc474-c3ab-40f8-af0e-8687c1d5a9ea,**Summary:**\n\nCNN correspondent Soledad O'Br...,4a27ec6ce44609cd09930cd0506c84a2,1782444978470,1,good,The summary effectively captures the main poin...,565160d69c38e66cd88e386937e582c5,1782445212012,**Summary:**\n\nCNN correspondent Soledad O'Br...
2,EXP_ID_9e3d06,5ed19dbb-4650-422d-ade2-baba76909dbd,**Summary:**\n\nWhen the Minneapolis bridge co...,09e33240d1189e653b2107d0170b7b26,1782444980965,1,good,The summary captures the main events and emoti...,32ad3a446a6cf19171ee8103dedb4293,1782445214068,**Summary:**\n\nWhen the Minneapolis bridge co...
3,EXP_ID_be1734,1a21d9bc-9865-4ad7-9b85-86600a3607a3,**Summary:**\n\nPresident Bush had five small ...,36d3a7535357f502a79d398a5954a018,1782444984954,1,good,The summary effectively captures the key point...,a3a3f6df00c13390d28ea1c9fcaf6921,1782445215853,**Summary:**\n\nPresident Bush had five small ...
4,EXP_ID_326413,c9f5975b-7647-4ed4-81cf-89517c261593,**Summary:**\n\nAtlanta Falcons quarterback Mi...,39d34a9125eaabd9b8f4e4e4bdff2cbe,1782444986838,1,good,The summary captures the key points of the ori...,42437440765442780483d265b4a9bfd0,1782445218229,**Summary:**\n\nAtlanta Falcons quarterback Mi...

In [33]:
meta_prompt = """
You are an expert in prompt optimization. You are given an ORIGINAL summarization prompt and PERFORMANCE DATA produced by running that prompt over a dataset. Each performance record contains the model's actual output and an LLM-judge evaluation (`label` = good/bad) with an `eval_explanation` describing WHY the summary was judged good or bad. Use this signal to rewrite the original prompt so that future summaries earn the "good" label.

ORIGINAL BASELINE PROMPT
========================
You are a helpful assistant that summarizes articles.
Summarize the following article in a concise manner:

========================

PERFORMANCE DATA (8 records: 3 bad, 5 good for contrast)
================
{feedback_samples}
================

HOW TO USE THIS DATA
1. Read every `eval_explanation`. The judge states concrete reasons a summary failed or passed.
2. Find the recurring failure pattern across the `bad` records — what do their explanations have
   in common? (e.g. missing specific context, omitted nuances, insufficient comprehensiveness.)
3. Contrast with the `good` records to infer what the judge rewards.
4. Translate those patterns into general, reusable instructions in the prompt — NOT fixes for
   these specific articles.

ALIGNMENT STRATEGY (derive from the explanations, do not hard-code these)
- If summaries are penalized for omitting important context/nuance → instruct the model to
  preserve key context, relationships, and consequential details from the source.
- If summaries are penalized for being too concise / not comprehensive → set explicit coverage
  expectations (capture all major points, not just the headline event).
- Keep whatever the `good` explanations praise (coherence, conciseness) intact.

RULES
Maintain Structure:
- Preserve every template variable from the original prompt verbatim ({{var}}).
- Do not change sections that are already working.
- Preserve the exact output/return-format instructions from the original prompt.

Avoid Overfitting:
- DO NOT copy any article text, summary, or explanation from the performance data into the prompt.
- DO NOT reference these specific examples (Carlos Alberto, Youssif, Bush veto, etc.).
- INSTEAD extract the ESSENCE of what separates good from bad summaries and express it as
  general principles. If you add few-shot examples, make them SYNTHETIC.

Goal: a prompt that generalizes to new documents, not one that memorizes this data.

OUTPUT FORMAT
Return the revised prompt as a JSON array of messages:
[
  {{"role": "system", "content": "..."}},
  {{"role": "user", "content": "..."}}
]

Then add a short "Reasoning" section (bulleted) explaining:
- The dominant failure pattern you found in the `bad` explanations
- Each change you made and which explanation(s) motivated it
"""

In [38]:
import json

response = chain.invoke(
    meta_prompt.format(
        feedback_samples=filtered_df[["output", "eval.summary_eval.label", "eval.summary_eval.explanation"]].to_string(index=False)
    )
)

# The chain returns plain text: a JSON array of messages, then a "Reasoning" section.
# raw_decode parses the leading JSON array and ignores the trailing prose.
start = response.index("[")
optimized_messages, end = json.JSONDecoder().raw_decode(response[start:])
reasoning = response[start + end:].strip()

print(reasoning)
optimized_messages

Reasoning

- Dominant failure pattern in the bad explanations:
  - Summaries were penalized for omitting important context, background, or consequential details, resulting in a lack of comprehensiveness or nuance.
  - The summaries were sometimes too concise, missing key relationships, background, or implications necessary for a full understanding.
- Changes made:
  - Added explicit instructions to capture all major points, key events, and significant relationships or consequences, addressing the lack of comprehensiveness noted in the bad explanations.
  - Instructed to preserve essential background and context, motivated by repeated feedback that missing these aspects led to a 'bad' label.
  - Warned against omitting consequential information or oversimplifying, directly targeting the main reason for summary failures.
  - Retained praise-worthy aspects from the good explanations: conciseness, coherence, independence from the original text, and clarity.
  - Emphasized balancing conciseness with comprehensiveness, as the good summaries were concise but still covered all necessary information.

[{'role': 'system',
  'content': "You are a helpful assistant that summarizes articles. Your summaries should be concise, coherent, and stand independently from the original text. However, do not sacrifice important context or nuance for brevity. Ensure your summary:\n\n- Captures all major points, key events, and significant relationships or consequences described in the article.\n- Preserves essential background, context, and any important details that contribute to a comprehensive understanding of the article's subject.\n- Avoids omitting consequential information or oversimplifying complex situations.\n- Remains clear, well-structured, and free of unnecessary details or direct copying from the original text.\n\nStrive for a balance between conciseness and comprehensiveness so the summary fully represents the article's main ideas and context."},
 {'role': 'user',
  'content': 'Summarize the following article in a concise manner:\n\n{article}'}]