# 05. Skill Optimization — dialog-summary SKILL.md
Optimize `dialog-summary/SKILL.md` against samsum gold summaries via Arize experiments.

In [1]:
!pip install -qqq arize arize-phoenix certifi urllib3 langchain-openai python-dotenv

In [2]:
import os, certifi
CA = certifi.where()
os.environ["SSL_CERT_FILE"] = CA
os.environ["REQUESTS_CA_BUNDLE"] = CA
os.environ["CURL_CA_BUNDLE"] = CA

from arize import ArizeClient
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

API_KEY = os.getenv("ARIZE_API_KEY")
SPACE_ID = os.getenv("ARIZE_SPACE_ID")
assert os.getenv("OPENAI_API_KEY"), "OPENAI_API_KEY not set (not in .env) — export it before running"

client = ArizeClient(api_key=API_KEY, request_verify=False)

# ---- demo config (single source of truth) ----
N_EXAMPLES   = 50
N_ITERATIONS = 3
GEN_MODEL    = "gpt-4.1-2025-04-14"
JUDGE_MODEL  = "gpt-4o-mini"
SKILL_PATH   = "dialog-summary/SKILL.md"
VERSIONS_DIR = "dialog-summary/versions"
DATASET_NAME = "samsum_small"

In [3]:
examples = client.datasets.list_examples(dataset=DATASET_NAME, space=SPACE_ID)
examples

  arize.pre_releases | WARNING | [BETA] datasets.list_examples is a beta API in Arize SDK v8.37.1 and may change without notice. If you experience unexpected failures, please upgrade to the most recent version of the package.

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

DatasetExampleListResponse(examples=[DatasetExample(id='00f72bad-ab78-4d51-9df7-e4be79905611', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Mary: Sorry, I didn't make it to your bday party :(\nNick: It's OK...\nMary: But I just got SOOO distracted! I forgot it was yesterday!\nNick: do tell!\nMary: I met this guy...\nNick: REALLY? I want details :D\nMary: Yeah, his name is Kirk and he's an architect...\nNick: OK, just your type then <file_gif>\nMary: And we ended up spending the whole week together. xD\nNick: A WEEK?\nMary: Yeah... It's madness, I'll tell you more this evening. Are we still on?\nNick: You bet we are!", 'summary': "Mary didn't come to Nick's birthday party. She met an architect named Kirk. Mary and Nick will meet in the evening."}), DatasetExample(id='02a40690-2e21-403c-b883-26e1b263e4d9', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Neville: Hi there, does anyone remember what date I got married on?\nDon: Are you serious?\nNeville: Dead serious. We're on vacation, and Tina's mad at me about something. I have a strange suspicion that this might have something to do with our wedding anniversary, but I have nowhere to check.\nWyatt: Hang on, I'll ask my wife.\nDon: Haha, someone's in a lot of trouble :D\nWyatt: September 17. I hope you remember the year ;)", 'summary': "Wyatt reminds Neville his wedding anniversary is on the 17th of September. Neville's wife is upset and it might be because Neville forgot about their anniversary."}), DatasetExample(id='04e31f6a-d3e7-42bf-8084-f980bf2e7efa', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Oli: I've talked to some people from the third year\nJacob: About the statistics exam?\nMarcia: What did they say?\nOli: Yeah, about the exam\nOli: We need to prepare for a battle\nJacob: So it will be difficult\nOli: They said it was the hardest exam ever\nMarcia: 😱\nOli: The questions were displayed on the screen \nOli: One minute per question and it disappears\nOli: They won't come back so if you didn't get your answer you're fucked\nMarcia: So we need to make the calculations really fast\nJacob: That's insane\nOli: I know\nOli: Very stressful\nMarcia: How are we even supposed to study for it?\nMarcia: With a timer?\nOli: I guess\nMarcia: Did anybody pass it last year\nOli: Some people did, but the majority had to take the second or even the third chance", 'summary': 'Oli, Jacob and Marcia have to prepare for a very hard statistics exam. Last year, people had only one minute to answer each question and then it disappeared.'}), DatasetExample(id='04e5763b-b8aa-40da-8e83-2661f6080ac5', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': 'Hannah: The motherfucker took my spot again\nPamela: Richard?\nAnne: I saw him parking... ', 'summary': "Richard took Hannah's parking spot again. Anne saw it."}), DatasetExample(id='08277e54-4725-4fa3-b122-833fc0f95640', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Isabella: fuck my life, I'm so not able to get up to work today\nIsabella: I need to call in sick :(\nOscar: haha, well you certainly had a good time at the Christmas party yesterday XD\nIsabella: shut up, you're a traitor\nIsabella: I told you to guard my glass\nIsabella: and my sobriety. You clearly failed!\nOscar: but you were having such fun, I didn't have a heart to stop it\nOscar: <file_photo>\nOscar: <file_photo>\nIsabella: you're so dead! Is that Jimmy from marketing department?\nOscar: yes indeed, it's him :D\nIsabella: I am a fallen woman, I cannot get back to the office now\nIsabella: <file_gif>\nOscar: oh come on, almost everybody was drunk\nOscar: so they won't remember a thing :D\nIsabella: I assure you, they tend to remember such things…\nOscar: <file_gif>", 'summary': 'Isabella feels bad after the Christmas party. She got drunk. She is ashamed to go back to work. '}), DatasetExample(id='0ba17510-9d05-4f31-b438-3cf2dfdd9ec8', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Leon: did you find the job yet?\nArthur: no bro, still unemployed :D\nLeon: hahaha, LIVING LIFE\nArthur: i love it, waking up at noon, watching sports - what else could a man want?\nLeon: a paycheck? ;)\nArthur: don't be mean... \nLeon: but seriously, my mate has an offer as a junior project manager at his company, are you interested?\nArthur: sure thing, do you have any details?\nLeon: <file_photo>\nArthur: that actually looks nice, should I reach out directly to your friend or just apply to this email address from the screenshot?\nLeon: it's his email, you can send your resume directly and I will mention to him who you are :)", 'summary': 'Arthur is still unemployed. Leon sends him a job offer for junior project manager position. Arthur is interested.'}), DatasetExample(id='0c153954-be1a-4952-a067-7f21f7685693', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Laura: ok , I'm done for today-)\nLaura: let me know once u're free and we come back home together\nKim: hmm.. 7?\nLaura: ok\nKim: cool, wait for me at work, I'll call once I get here", 'summary': 'Laura will pick up Kim from work around 7, and they will come back home together.'}), DatasetExample(id='13e54657-3a33-4f6a-8ca0-38de969d592d', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Tom: How’s the weather in Poland now?\nJustin: It’s getting cooler. Ain't no sunshine and winter’s coming 😊\nTom: Have you seen the last episode of Game of Thrones?\nJustin: Not yet. Can’t wait to see it 😊", 'summary': "It's getting cooler in Poland, because winter is coming. Justin hasn't seen the last episode of Game of Thrones yet."}), DatasetExample(id='13fc0248-7614-4ec5-a4f6-42bd203de63c', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': 'Frank: Hi Peter has brought me to Sports Direct store at the top of \nRosie: Ok thanks will look out for you there\nFrank: We are on the ground floor\nRosie: ok\nFrank: Outside Morrisons\nRosie: On my way\nFrank: We might be upstairs later so look there too\nRosie: ok I will - see you soon xxx', 'summary': 'Rosie is on her way to meet Frank and will have to find him at Sports Direct.'}), DatasetExample(id='14cc88a5-ba3b-4aba-acb3-5ba032c89eb4', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Gunther: did you pay for coffee?\nChandler: uhh.. i guess not xDbut it's okay i'll pay him tomorrow\nGunther: -_-", 'summary': 'Chandler will pay for his coffee tomorrow.'}), DatasetExample(id='1ae589f6-3e7d-43aa-8637-845761c0b3ad', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Jack: Where are you? I can't find you.\nOlivia: carriage 3!\nJack: I'm in 15 I believe :/ it's so crowded\nOlivia: But slowly you can get through.\nJack: I am not sure, there are people sitting, staying, puking everywhere. It's a mess\nOlivia: C'mon, it's a busy weekend\nJack: I already hate this trip.\nOlivia: Just don't make a drama, come here.\nJack: Do you have the tickets? I can't find mine.\nOlivia: I have both of them, so you have no choice anyway. You should come here asap :P", 'summary': 'Jack has to find Olivia in carriage 3, because she has their tickets.'}), DatasetExample(id='1af6b2e0-b070-4ada-ac3f-a427be0c3150', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Sarah: I found a song on youtube and I think you'll like it\nJames: What song?\nSarah: <file_other>\nJames: Oh. I know it! \nJames: I heard it before in some compilation\nSarah: I can't stop playing it over and over\nJames: That's exactly how I know lyrics to all of the songs on my playlist :D\nSarah: Haha. No lyrics here though. Instrumental ;D\nJames: Instrumental songs are different kind of music. \nJames: But you have to remember that the activity you do when you listen to this song\nJames: Is the actvity your brain will connect to the song\nJames: And everytime you play this song at home\nJames: You'll be thinking of your work\nSarah: Yeah, I know that. That's why we sometimes say - I used to like that song, but now it just reminds me of bad memories\nJames: Yup. Everytime you change your partner, you have to get rid of your favorite music :D\nSarah: Hahaha. True, true.", 'summary': 'Sarah sends James an instrumental song he might like. James knows the song. The brain connects the songs to the context they were played in and brings to mind the associated memories.'}), DatasetExample(id='1ddcd47a-9581-450a-a2de-5eeb27d82aab', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Linda: I'm going to have my room painted\nLinda: Can't decide what colors would best express my personality\nLinda: I'm considering advices, do you have one for me maybe? :)\nBrian: Fitting your personality... hmm\nBrian: I consider you an enthusiastic and lively person and the color for it is yellow\nBrian: On the other hand you can be calm and steady and they say those qualities are expressed in greyness\nBrian: So yellow & grey, how do you like the idea? :D\nLinda: Wow, I'm impressed!\nLinda: You've just paid me a compliment and come up with interesting colors!\nBrian: Well, those are actually facts :)\nBrian: Are you going to make use of the colors?\nLinda: Actually, I was planning to ask a few friends and then sum all the ideas up\nLinda: But now I think I don't need to do any further research\nLinda: Asking you for help was a bull's-eye! :D\nBrian: Perfection! :D\nBrian: I'll come and check the results of your work soon, it'll be a nice chance for us to talk :)\nLinda: Sure, feel invited!", 'summary': "According to Brian, colors that match Linda's personality are yellow and grey."}), DatasetExample(id='241fd291-5bb2-4b28-870e-6cc04ca6ba56', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Amanda: I baked  cookies. Do you want some?\nJerry: Sure!\nAmanda: I'll bring you tomorrow :-)", 'summary': 'Amanda baked cookies and will bring Jerry some tomorrow.'}), DatasetExample(id='255ec877-9638-4aa8-ace4-ddd18d0e0db6', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Max: I'm so sorry Lucas. I don't know what got into me.\nLucas: .......\nLucas: I don't know either.\nMason: that was really fucked up Max\nMax: I know. I'm so sorry :(.\nLucas: I don't know, man.\nMason: what were you thinking??\nMax: I wasn't.\nMason: yea\nMax: Can we please meet and talk this through? Please.\nLucas: Ok. I'll think about it and let you know.\nMax: Thanks...", 'summary': 'Max is sorry about his behaviour so wants to meet up with Lucas and Mason. Lucas will let him know. '}), DatasetExample(id='273ecac1-f35b-4e55-96c4-14b3dd72a92e', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': 'Sophia: What should I get them?\nMonica: How should I know?\nSophia: come on help me out\nMonica: I dont know really Im bad at buying gifts\nSophia: maybe some day spa gift card\nMonica: maybe\nSophia: youre not really helpful :P\nMonica: Told ya... bad at gifts', 'summary': "Sophie doesn't know what to buy for a gift. She wants Monica's help. She is considering buying a day spa gift card. Monica is bad at buying gifts."}), DatasetExample(id='292f6e97-055f-4e60-b150-402d9921f3f5', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Lucia: I need my hair cut.\nLucia: When can I come? I've got some time on Thursday and Friday.\nEric: Lucia! My dear!\nEric: Are you sure? After all, you had your hairstyle done a week ago.\nEric: What's the matter? Don't you like it?\nLucia: I like it very much and I regret to lose it.\nLucia: But I'm changing the job and my hair must be shorter...\nEric: I see. You'll tell me everything in detail once you're here, in my beauty salon.\nEric: I suggest Friday at 3 p.m. Is it fine for you?\nLucia: Sure, perfect.\nEric: Fantastic, have a nice day then.\nLucia: Thanks, bye.", 'summary': 'Lucia needs a new hairstyle due to a change of work and she makes an appointment with Eric for Friday 3 p.m.'}), DatasetExample(id='31c61f56-2095-40ce-ab77-defad3d230a3', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Bradley: It's very safe. Not like they make it look on TV\nJulianna: Hehe I told them that also that tv will never show anything nice\nBradley: True...\nJulianna: But in general I think Europe is safer because here we have different law. I mean we have too much law\nBradley: Haha\nJulianna: E.g here if a teacher even touches a children's arm, he or she can have problems with police and law. Because it might be a sign of pedophilia or children sexual harassment\nBradley: Ok\nJulianna: That's sick a bit hehe but on the other hand sometimes it's ok\nBradley: Haha ok how ?\nJulianna: Because there are pedophiles in that world\nBradley: They are everywhere\nJulianna: And when someone hits a child that person should be punished", 'summary': "Julianna tells Bradley about Europe's law and the approach towards pedophiles."}), DatasetExample(id='32f57719-2a24-405e-9f11-d38f4cdbb9c7', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Sam: I just got my 1st credit card!\nTom: Well, congrats and sorry!\nSam: Y sry?\nTom: Aren't u afraid of getting into debts?\nSam: No, not really. Should I be?\nTom: I think u should.", 'summary': 'Sam got her first credit card.'}), DatasetExample(id='370ec4f5-5b81-4b9d-9c58-481ae2bf939c', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Kyle: hey u got maths homework?\nPatrick: um.. not yet :D\nKyle: hahaha what do you mean not yet\nKyle: it's for tomorrow\nKyle: i just reminded you didn't i hahahah\nPatrick: XD\nKyle: well good luck then\nPatrick: tx xD guess i'm gonna need it XD", 'summary': 'Kyle reminds Patrick about their math homework for tomorrow.'}), DatasetExample(id='39d97bf2-3d3b-47d3-a8f7-3cdd0d492f1f', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': 'Hyatt: watch channel 6 now\nNickleby: whats on?\nHyatt: ah i see is that Stu?\nPalin: himself!\nNickleby: couldnt miss it :)', 'summary': 'Stu is on channel 6 now.'}), DatasetExample(id='417c55d9-1278-4ea8-8e66-323166d28a33', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Mary: Hi <3\nPeter: Hey gorgeous ;)\nMary: What's up\nPeter: Not much, jsut thinking about you \nMary: Aww I miss you so much :(\nPeter: I know baby but ill be back home in 2 days. The we can do whatever you want :*\nMary: Whatever I want, huh? 3:)\nPeter: ;)\nMary: I was actually hoping to cash in on that raincheck :) We haven't been on a date for quite a while... :/\nPeter: I'ld like that :)\nMary: :)", 'summary': 'Peter will be back home in 2 days. Mary would like to go on a date when he gets back.'}), DatasetExample(id='4370dd82-e948-4ad4-806f-fdadb30de4fd', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': 'Connor: hello can you tell me what songs did they play at the gig in Berlin?\nKyle: their official profile tweeted the set list a couple hours ago\nConnor: ok cool thanks\nKyle: cheers', 'summary': "Connor is looking for a playlist from the Berlin concert. Kyle directs him to the band's official Twitter account."}), DatasetExample(id='48a4b964-1ec4-41e1-8f80-1c3c06049ab7', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Karen: Where'd you buy this dress you had at the wedding?\nSamara: Oh, from an online shop\nSamara: Hold on\nSamara: <file_other>\nSamara: That's the one\nKaren: Wow thanks\nSamara: Youre welcome!\nKaren: Oooh, they have some neat stuff there\nSamara: Yeah, I was so happy when i disovered it\nSamara: There's few places where I shop regularly, most of the time I'm kind of all over the place\nKaren: Same here\nSamara: But I've already bought several skirts and blouses from this shop too, so I'll probably become a more frequent customer ;)", 'summary': 'Samara bought the dress she had at the wedding in an online shop and she was happy when she discovered it.'}), DatasetExample(id='4a20736d-0695-4771-a335-d1fc7d65f696', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), annotations=None, additional_properties={'dialogue': "Hal: Have you got any homework for tomorrow?\nAmy: no dad\nHal: ru sure?\nAmy: told ya\nHal: You know mum's not home today.\nAmy: I know, I can use the microwave\nHal: good girl. I'll be home around 6\nAmy: yeah right\nHal: what do you mean\nAmy: sry dad but you're never ever home at 6\nHal: i suppose you;re right. but I'll try today\nAmy: ok. can I go to Alex?\nHal: ok, but be back home before 7. we'll have dinner together\nAmy: ok dad\nHal: and if you really have no homework to do\nAmy: sure thing dad", 'summary': 'Amy and Hal will have dinner together when he is back home before 7.'}), DatasetExample(id='4a3652f0-cb44-4f8a-938f-89b1e6b4636d', created_at=datetime.datetime(2026, 6, 26, 3, 25, 16, tzinfo=TzInfo(0)), updated_at=da

In [4]:
from langchain_core.output_parsers import StrOutputParser
from langchain_openai import ChatOpenAI

gen_llm = ChatOpenAI(model=GEN_MODEL, temperature=0.0)
gen_chain = gen_llm | StrOutputParser()

def read_skill() -> str:
    with open(SKILL_PATH, "r") as f:
        return f.read()

def run_skill(dataset_row) -> str:
    """Use the full SKILL.md text as the system prompt over one dialogue."""
    skill = read_skill()
    dialogue = dataset_row["dialogue"]
    messages = [
        ("system", skill),
        ("human", f"Summarize this dialogue:\n\n{dialogue}"),
    ]
    return gen_chain.invoke(messages)

In [5]:
# smoke test on one example (does NOT hit Arize)
_sample = examples.to_df().iloc[0] if hasattr(examples, "to_df") else pd.DataFrame(examples).iloc[0]
print("DIALOGUE:\n", _sample["dialogue"][:400])
print("\nGOLD:\n", _sample["summary"])
print("\nSKILL OUTPUT:\n", run_skill(_sample))

DIALOGUE:
 Mary: Sorry, I didn't make it to your bday party :(
Nick: It's OK...
Mary: But I just got SOOO distracted! I forgot it was yesterday!
Nick: do tell!
Mary: I met this guy...
Nick: REALLY? I want details :D
Mary: Yeah, his name is Kirk and he's an architect...
Nick: OK, just your type then <file_gif>
Mary: And we ended up spending the whole week together. xD
Nick: A WEEK?
Mary: Yeah... It's madness,

GOLD:
 Mary didn't come to Nick's birthday party. She met an architect named Kirk. Mary and Nick will meet in the evening.

SKILL OUTPUT:
 Mary apologizes to Nick for missing his birthday party because she was distracted after meeting someone new, Kirk, with whom she spent the week. She promises to share more details when they meet later that evening, and Nick confirms their plans.

In [6]:
from phoenix.evals import llm_classify, OpenAIModel
from arize.experiments import EvaluationResult

skill_eval_template = """
You are judging whether a generated summary of a dialogue matches the reference (gold) summary.
    [BEGIN DATA]
    ************
    [Generated Summary]: {output}
    ************
    [Reference Summary]: {reference}
    [END DATA]

Compare the Generated Summary to the Reference Summary. Judge whether the Generated Summary is
faithful (no invented facts, correct who-said/wanted-what), covers the same key decisions/requests/
plans as the Reference, and is comparably concise. Your response must be a single word, either
"good" or "bad", with no other text. "good" = faithful, complete on key points, and concise
relative to the Reference. "bad" = misses key points, misattributes, invents facts, or is not concise.
"""

def skill_eval(output, dataset_row) -> EvaluationResult:
    eval_df = llm_classify(
        data=pd.DataFrame([{"output": output, "reference": dataset_row["summary"]}]),
        template=skill_eval_template,
        model=OpenAIModel(model=JUDGE_MODEL),
        rails=["good", "bad"],
        provide_explanation=True,
    )
    label = eval_df["label"][0]
    score = 1 if label == "good" else 0
    return EvaluationResult(label=label, score=score, explanation=eval_df["explanation"][0])

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
# sanity: a good summary (the gold itself) should score 1; a junk summary should score 0
print("gold-vs-gold:", skill_eval(_sample["summary"], _sample).label, "(expect good)")
print("junk        :", skill_eval("They talked about nothing.", _sample).label, "(expect bad)")

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.51s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.52s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

gold-vs-gold: good (expect good)

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.19s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.19s/it

junk        : bad (expect bad)

## Task 4: Baseline experiment `skill-v0` + feedback collection

Run the first Arize experiment (`task=run_skill`, `evaluators=[skill_eval]`) over `samsum_small`, then collect a small mixed sample of "bad"/"good" judged rows to feed the optimizer in later tasks.

In [8]:
def _delete_experiment_if_exists(version_name: str):
    """Idempotency: drop any prior experiment with this name so the notebook is re-runnable
    (Arize rejects experiments.run when the name already exists on the dataset)."""
    existing = client.experiments.list(space=SPACE_ID, dataset=DATASET_NAME)
    for e in existing.experiments:
        if e.name == version_name:
            client.experiments.delete(experiment=e.id, space=SPACE_ID, dataset=DATASET_NAME)

def run_experiment(version_name: str):
    _delete_experiment_if_exists(version_name)
    # experiments.run returns (experiment, results_df); we use the returned df directly.
    # NOTE: client.experiments.list_runs(...).to_df() is buggy in arize SDK v8.37.1
    # (raises pydantic ValidationError: ExperimentRun.id is None), so we avoid it.
    experiment, eval_df = client.experiments.run(
        name=version_name,
        dataset=DATASET_NAME,
        space=SPACE_ID,
        task=run_skill,
        evaluators=[skill_eval],
    )
    return experiment, eval_df

def mean_score(eval_df) -> float:
    return float(eval_df["eval.skill_eval.score"].astype(float).mean())

def collect_feedback(eval_df, n_bad: int = 3, n_good: int = 5):
    bad  = eval_df[eval_df["eval.skill_eval.label"] == "bad"].head(n_bad)
    good = eval_df[eval_df["eval.skill_eval.label"] == "good"].head(n_good)
    return pd.concat([bad, good])

In [9]:
exp_v0, eval_v0 = run_experiment("skill-v0")
print("columns:", list(eval_v0.columns))
print("skill-v0 mean score:", mean_score(eval_v0))
eval_v0.head()

  arize.pre_releases | WARNING | [BETA] experiments.list is a beta API in Arize SDK v8.37.1 and may change without notice. If you experience unexpected failures, please upgrade to the most recent version of the package.

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

  arize.pre_releases | WARNING | [BETA] experiments.delete is a beta API in Arize SDK v8.37.1 and may change without notice. If you experience unexpected failures, please upgrade to the most recent version of the package.

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

  arize.experiments.functions | INFO | 🧪 Experiment started.

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running tasks |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

running tasks |          | 1/100 (1.0%) | ⏳ 00:01<02:19 |  1.41s/it

running tasks |▏         | 2/100 (2.0%) | ⏳ 00:02<01:58 |  1.21s/it

running tasks |▎         | 3/100 (3.0%) | ⏳ 00:03<02:03 |  1.27s/it

running tasks |▍         | 4/100 (4.0%) | ⏳ 00:05<02:06 |  1.32s/it

running tasks |▌         | 5/100 (5.0%) | ⏳ 00:06<01:56 |  1.23s/it

running tasks |▌         | 6/100 (6.0%) | ⏳ 00:07<02:00 |  1.29s/it

running tasks |▋         | 7/100 (7.0%) | ⏳ 00:09<02:09 |  1.39s/it

running tasks |▊         | 8/100 (8.0%) | ⏳ 00:10<02:07 |  1.38s/it

running tasks |▉         | 9/100 (9.0%) | ⏳ 00:11<02:01 |  1.33s/it

running tasks |█         | 10/100 (10.0%) | ⏳ 00:13<01:59 |  1.33s/it

running tasks |█         | 11/100 (11.0%) | ⏳ 00:14<01:47 |  1.21s/it

running tasks |█▏        | 12/100 (12.0%) | ⏳ 00:15<01:39 |  1.13s/it

running tasks |█▎        | 13/100 (13.0%) | ⏳ 00:16<01:43 |  1.19s/it

running tasks |█▍        | 14/100 (14.0%) | ⏳ 00:18<01:57 |  1.37s/it

running tasks |█▌        | 15/100 (15.0%) | ⏳ 00:19<01:55 |  1.36s/it

running tasks |█▌        | 16/100 (16.0%) | ⏳ 00:20<01:49 |  1.31s/it

running tasks |█▋        | 17/100 (17.0%) | ⏳ 00:21<01:43 |  1.24s/it

running tasks |█▊        | 18/100 (18.0%) | ⏳ 00:22<01:39 |  1.22s/it

running tasks |█▉        | 19/100 (19.0%) | ⏳ 00:24<01:46 |  1.31s/it

running tasks |██        | 20/100 (20.0%) | ⏳ 00:25<01:39 |  1.24s/it

running tasks |██        | 21/100 (21.0%) | ⏳ 00:26<01:37 |  1.23s/it

running tasks |██▏       | 22/100 (22.0%) | ⏳ 00:28<01:39 |  1.27s/it

running tasks |██▎       | 23/100 (23.0%) | ⏳ 00:29<01:40 |  1.31s/it

running tasks |██▍       | 24/100 (24.0%) | ⏳ 00:30<01:38 |  1.30s/it

running tasks |██▌       | 25/100 (25.0%) | ⏳ 00:32<01:47 |  1.43s/it

running tasks |██▌       | 26/100 (26.0%) | ⏳ 00:33<01:39 |  1.34s/it

running tasks |██▋       | 27/100 (27.0%) | ⏳ 00:34<01:31 |  1.25s/it

running tasks |██▊       | 28/100 (28.0%) | ⏳ 00:35<01:29 |  1.25s/it

running tasks |██▉       | 29/100 (29.0%) | ⏳ 00:37<01:36 |  1.36s/it

running tasks |███       | 30/100 (30.0%) | ⏳ 00:39<01:42 |  1.46s/it

running tasks |███       | 31/100 (31.0%) | ⏳ 00:40<01:38 |  1.43s/it

running tasks |███▏      | 32/100 (32.0%) | ⏳ 00:41<01:33 |  1.38s/it

running tasks |███▎      | 33/100 (33.0%) | ⏳ 00:42<01:24 |  1.27s/it

running tasks |███▍      | 34/100 (34.0%) | ⏳ 00:44<01:24 |  1.28s/it

running tasks |███▌      | 35/100 (35.0%) | ⏳ 00:45<01:20 |  1.24s/it

running tasks |███▌      | 36/100 (36.0%) | ⏳ 00:46<01:25 |  1.33s/it

running tasks |███▋      | 37/100 (37.0%) | ⏳ 00:48<01:21 |  1.29s/it

running tasks |███▊      | 38/100 (38.0%) | ⏳ 00:49<01:18 |  1.27s/it

running tasks |███▉      | 39/100 (39.0%) | ⏳ 00:50<01:15 |  1.23s/it

running tasks |████      | 40/100 (40.0%) | ⏳ 00:51<01:14 |  1.24s/it

running tasks |████      | 41/100 (41.0%) | ⏳ 00:53<01:15 |  1.29s/it

running tasks |████▏     | 42/100 (42.0%) | ⏳ 00:54<01:19 |  1.38s/it

running tasks |████▎     | 43/100 (43.0%) | ⏳ 00:55<01:15 |  1.32s/it

running tasks |████▍     | 44/100 (44.0%) | ⏳ 00:57<01:15 |  1.36s/it

running tasks |████▌     | 45/100 (45.0%) | ⏳ 00:58<01:14 |  1.36s/it

running tasks |████▌     | 46/100 (46.0%) | ⏳ 00:59<01:11 |  1.33s/it

running tasks |████▋     | 47/100 (47.0%) | ⏳ 01:01<01:06 |  1.25s/it

running tasks |████▊     | 48/100 (48.0%) | ⏳ 01:02<01:08 |  1.32s/it

running tasks |████▉     | 49/100 (49.0%) | ⏳ 01:03<01:07 |  1.33s/it

running tasks |█████     | 50/100 (50.0%) | ⏳ 01:05<01:05 |  1.31s/it

running tasks |█████     | 51/100 (51.0%) | ⏳ 01:06<00:59 |  1.22s/it

running tasks |█████▏    | 52/100 (52.0%) | ⏳ 01:07<00:56 |  1.18s/it

running tasks |█████▎    | 53/100 (53.0%) | ⏳ 01:08<00:52 |  1.12s/it

running tasks |█████▍    | 54/100 (54.0%) | ⏳ 01:09<00:51 |  1.12s/it

running tasks |█████▌    | 55/100 (55.0%) | ⏳ 01:10<00:54 |  1.21s/it

running tasks |█████▌    | 56/100 (56.0%) | ⏳ 01:12<00:57 |  1.31s/it

running tasks |█████▋    | 57/100 (57.0%) | ⏳ 01:14<01:03 |  1.47s/it

running tasks |█████▊    | 58/100 (58.0%) | ⏳ 01:15<01:00 |  1.44s/it

running tasks |█████▉    | 59/100 (59.0%) | ⏳ 01:16<00:56 |  1.38s/it

running tasks |██████    | 60/100 (60.0%) | ⏳ 01:17<00:53 |  1.33s/it

running tasks |██████    | 61/100 (61.0%) | ⏳ 01:19<00:50 |  1.30s/it

running tasks |██████▏   | 62/100 (62.0%) | ⏳ 01:24<01:39 |  2.62s/it

running tasks |██████▎   | 63/100 (63.0%) | ⏳ 01:25<01:19 |  2.14s/it

running tasks |██████▍   | 64/100 (64.0%) | ⏳ 01:27<01:07 |  1.87s/it

running tasks |██████▌   | 65/100 (65.0%) | ⏳ 01:28<00:55 |  1.59s/it

running tasks |██████▌   | 66/100 (66.0%) | ⏳ 01:29<00:48 |  1.41s/it

running tasks |██████▋   | 67/100 (67.0%) | ⏳ 01:30<00:44 |  1.33s/it

running tasks |██████▊   | 68/100 (68.0%) | ⏳ 01:31<00:39 |  1.23s/it

running tasks |██████▉   | 69/100 (69.0%) | ⏳ 01:32<00:41 |  1.35s/it

running tasks |███████   | 70/100 (70.0%) | ⏳ 01:33<00:37 |  1.26s/it

running tasks |███████   | 71/100 (71.0%) | ⏳ 01:34<00:33 |  1.16s/it

running tasks |███████▏  | 72/100 (72.0%) | ⏳ 01:35<00:31 |  1.11s/it

running tasks |███████▎  | 73/100 (73.0%) | ⏳ 01:37<00:31 |  1.18s/it

running tasks |███████▍  | 74/100 (74.0%) | ⏳ 01:38<00:31 |  1.19s/it

running tasks |███████▌  | 75/100 (75.0%) | ⏳ 01:39<00:30 |  1.24s/it

running tasks |███████▌  | 76/100 (76.0%) | ⏳ 01:40<00:28 |  1.21s/it

running tasks |███████▋  | 77/100 (77.0%) | ⏳ 01:42<00:30 |  1.32s/it

running tasks |███████▊  | 78/100 (78.0%) | ⏳ 01:43<00:28 |  1.28s/it

running tasks |███████▉  | 79/100 (79.0%) | ⏳ 01:44<00:25 |  1.19s/it

running tasks |████████  | 80/100 (80.0%) | ⏳ 01:45<00:23 |  1.18s/it

running tasks |████████  | 81/100 (81.0%) | ⏳ 01:47<00:26 |  1.39s/it

running tasks |████████▏ | 82/100 (82.0%) | ⏳ 01:48<00:23 |  1.32s/it

running tasks |████████▎ | 83/100 (83.0%) | ⏳ 01:49<00:21 |  1.27s/it

running tasks |████████▍ | 84/100 (84.0%) | ⏳ 01:51<00:19 |  1.23s/it

running tasks |████████▌ | 85/100 (85.0%) | ⏳ 01:52<00:18 |  1.22s/it

running tasks |████████▌ | 86/100 (86.0%) | ⏳ 01:53<00:16 |  1.19s/it

running tasks |████████▋ | 87/100 (87.0%) | ⏳ 01:54<00:14 |  1.13s/it

running tasks |████████▊ | 88/100 (88.0%) | ⏳ 01:55<00:14 |  1.21s/it

running tasks |████████▉ | 89/100 (89.0%) | ⏳ 01:57<00:13 |  1.20s/it

running tasks |█████████ | 90/100 (90.0%) | ⏳ 01:58<00:12 |  1.23s/it

running tasks |█████████ | 91/100 (91.0%) | ⏳ 01:59<00:10 |  1.19s/it

running tasks |█████████▏| 92/100 (92.0%) | ⏳ 02:00<00:10 |  1.25s/it

running tasks |█████████▎| 93/100 (93.0%) | ⏳ 02:01<00:08 |  1.21s/it

running tasks |█████████▍| 94/100 (94.0%) | ⏳ 02:03<00:07 |  1.19s/it

running tasks |█████████▌| 95/100 (95.0%) | ⏳ 02:04<00:06 |  1.20s/it

running tasks |█████████▌| 96/100 (96.0%) | ⏳ 02:05<00:04 |  1.17s/it

running tasks |█████████▋| 97/100 (97.0%) | ⏳ 02:06<00:03 |  1.27s/it

running tasks |█████████▊| 98/100 (98.0%) | ⏳ 02:08<00:02 |  1.23s/it

running tasks |█████████▉| 99/100 (99.0%) | ⏳ 02:09<00:01 |  1.23s/it

running tasks |██████████| 100/100 (100.0%) | ⏳ 02:10<00:00 |  1.20s/it

running tasks |██████████| 100/100 (100.0%) | ⏳ 02:10<00:00 |  1.30s/it

  arize.experiments.functions | INFO | ✅ Task runs completed.
Tasks Summary (07/03/26 11:02 AM +0900)
---------------------------------------
   n_examples  n_runs  n_errors
0         100     100         0

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running experiment evaluations |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.08s/it

running experiment evaluations |          | 1/100 (1.0%) | ⏳ 00:02<03:49 |  2.32s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:06<00:00 |  6.50s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:06<00:00 |  6.50s/it

running experiment evaluations |▏         | 2/100 (2.0%) | ⏳ 00:09<08:03 |  4.93s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.00s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.00s/it

running experiment evaluations |▎         | 3/100 (3.0%) | ⏳ 00:11<06:00 |  3.71s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.44s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.44s/it

running experiment evaluations |▍         | 4/100 (4.0%) | ⏳ 00:14<05:17 |  3.31s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.18s/it

running experiment evaluations |▌         | 5/100 (5.0%) | ⏳ 00:16<04:44 |  2.99s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it

running experiment evaluations |▌         | 6/100 (6.0%) | ⏳ 00:18<04:07 |  2.64s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.14s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.14s/it

running experiment evaluations |▋         | 7/100 (7.0%) | ⏳ 00:20<03:58 |  2.56s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

running experiment evaluations |▊         | 8/100 (8.0%) | ⏳ 00:23<03:55 |  2.56s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.44s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.45s/it

running experiment evaluations |▉         | 9/100 (9.0%) | ⏳ 00:26<03:56 |  2.60s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

running experiment evaluations |█         | 10/100 (10.0%) | ⏳ 00:28<03:47 |  2.53s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

running experiment evaluations |█         | 11/100 (11.0%) | ⏳ 00:30<03:35 |  2.42s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

running experiment evaluations |█▏        | 12/100 (12.0%) | ⏳ 00:32<03:27 |  2.36s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.13s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.14s/it

running experiment evaluations |█▎        | 13/100 (13.0%) | ⏳ 00:35<03:26 |  2.37s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

running experiment evaluations |█▍        | 14/100 (14.0%) | ⏳ 00:37<03:18 |  2.31s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

running experiment evaluations |█▌        | 15/100 (15.0%) | ⏳ 00:39<03:12 |  2.27s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

running experiment evaluations |█▌        | 16/100 (16.0%) | ⏳ 00:41<03:07 |  2.24s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

running experiment evaluations |█▋        | 17/100 (17.0%) | ⏳ 00:43<02:55 |  2.12s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.16s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

running experiment evaluations |█▊        | 18/100 (18.0%) | ⏳ 00:45<03:01 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.52s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.52s/it

running experiment evaluations |█▉        | 19/100 (19.0%) | ⏳ 00:48<03:12 |  2.38s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.81s/it

running experiment evaluations |██        | 20/100 (20.0%) | ⏳ 00:50<03:02 |  2.29s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.76s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

running experiment evaluations |██        | 21/100 (21.0%) | ⏳ 00:52<02:54 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

running experiment evaluations |██▏       | 22/100 (22.0%) | ⏳ 00:55<02:59 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.74s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it

running experiment evaluations |██▎       | 23/100 (23.0%) | ⏳ 00:57<02:50 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.78s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.78s/it

running experiment evaluations |██▍       | 24/100 (24.0%) | ⏳ 01:00<03:06 |  2.46s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.52s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.53s/it

running experiment evaluations |██▌       | 25/100 (25.0%) | ⏳ 01:03<03:12 |  2.56s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.29s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.29s/it

running experiment evaluations |██▌       | 26/100 (26.0%) | ⏳ 01:07<03:53 |  3.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.05s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

running experiment evaluations |██▋       | 27/100 (27.0%) | ⏳ 01:10<03:32 |  2.91s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.77s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.77s/it

running experiment evaluations |██▊       | 28/100 (28.0%) | ⏳ 01:13<03:31 |  2.94s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.39s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.40s/it

running experiment evaluations |██▉       | 29/100 (29.0%) | ⏳ 01:15<03:23 |  2.86s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

running experiment evaluations |███       | 30/100 (30.0%) | ⏳ 01:17<02:59 |  2.57s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.68s/it

running experiment evaluations |███       | 31/100 (31.0%) | ⏳ 01:20<03:04 |  2.68s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

running experiment evaluations |███▏      | 32/100 (32.0%) | ⏳ 01:22<02:52 |  2.54s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.10s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.10s/it

running experiment evaluations |███▎      | 33/100 (33.0%) | ⏳ 01:25<02:46 |  2.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.39s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.39s/it

running experiment evaluations |███▍      | 34/100 (34.0%) | ⏳ 01:27<02:47 |  2.53s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.08s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.08s/it

running experiment evaluations |███▌      | 35/100 (35.0%) | ⏳ 01:31<03:00 |  2.78s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.89s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.89s/it

running experiment evaluations |███▌      | 36/100 (36.0%) | ⏳ 01:33<02:45 |  2.59s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

running experiment evaluations |███▋      | 37/100 (37.0%) | ⏳ 01:35<02:36 |  2.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.93s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.93s/it

running experiment evaluations |███▊      | 38/100 (38.0%) | ⏳ 01:37<02:28 |  2.39s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.26s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

running experiment evaluations |███▉      | 39/100 (39.0%) | ⏳ 01:40<02:28 |  2.43s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.16s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.16s/it

running experiment evaluations |████      | 40/100 (40.0%) | ⏳ 01:42<02:25 |  2.43s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.74s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.74s/it

running experiment evaluations |████      | 41/100 (41.0%) | ⏳ 01:44<02:15 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.35s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.36s/it

running experiment evaluations |████▏     | 42/100 (42.0%) | ⏳ 01:47<02:18 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.13s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.14s/it

running experiment evaluations |████▎     | 43/100 (43.0%) | ⏳ 01:49<02:16 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.68s/it

running experiment evaluations |████▍     | 44/100 (44.0%) | ⏳ 01:52<02:23 |  2.56s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.04s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.04s/it

running experiment evaluations |████▌     | 45/100 (45.0%) | ⏳ 01:54<02:16 |  2.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.63s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.64s/it

running experiment evaluations |████▌     | 46/100 (46.0%) | ⏳ 01:56<02:04 |  2.31s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it

running experiment evaluations |████▋     | 47/100 (47.0%) | ⏳ 01:58<01:57 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

running experiment evaluations |████▊     | 48/100 (48.0%) | ⏳ 02:01<01:55 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

running experiment evaluations |████▉     | 49/100 (49.0%) | ⏳ 02:03<01:49 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

running experiment evaluations |█████     | 50/100 (50.0%) | ⏳ 02:04<01:42 |  2.05s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

running experiment evaluations |█████     | 51/100 (51.0%) | ⏳ 02:07<01:42 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.28s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.28s/it

running experiment evaluations |█████▏    | 52/100 (52.0%) | ⏳ 02:09<01:46 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.57s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.57s/it

running experiment evaluations |█████▎    | 53/100 (53.0%) | ⏳ 02:12<01:52 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.95s/it

running experiment evaluations |█████▍    | 54/100 (54.0%) | ⏳ 02:15<02:01 |  2.64s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.09s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.10s/it

running experiment evaluations |█████▌    | 55/100 (55.0%) | ⏳ 02:18<02:08 |  2.86s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.31s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.32s/it

running experiment evaluations |█████▌    | 56/100 (56.0%) | ⏳ 02:21<02:02 |  2.77s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

running experiment evaluations |█████▋    | 57/100 (57.0%) | ⏳ 02:24<01:56 |  2.70s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

running experiment evaluations |█████▊    | 58/100 (58.0%) | ⏳ 02:26<01:44 |  2.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.58s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.58s/it

running experiment evaluations |█████▉    | 59/100 (59.0%) | ⏳ 02:29<01:58 |  2.89s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

running experiment evaluations |██████    | 60/100 (60.0%) | ⏳ 02:32<01:49 |  2.73s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.78s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.79s/it

running experiment evaluations |██████    | 61/100 (61.0%) | ⏳ 02:35<01:50 |  2.83s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.26s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

running experiment evaluations |██████▏   | 62/100 (62.0%) | ⏳ 02:37<01:43 |  2.74s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.63s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.63s/it

running experiment evaluations |██████▎   | 63/100 (63.0%) | ⏳ 02:39<01:31 |  2.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

running experiment evaluations |██████▍   | 64/100 (64.0%) | ⏳ 02:42<01:29 |  2.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.28s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.28s/it

running experiment evaluations |██████▌   | 65/100 (65.0%) | ⏳ 02:44<01:27 |  2.50s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.76s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.76s/it

running experiment evaluations |██████▌   | 66/100 (66.0%) | ⏳ 02:46<01:20 |  2.36s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

running experiment evaluations |██████▋   | 67/100 (67.0%) | ⏳ 02:49<01:19 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.85s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.85s/it

running experiment evaluations |██████▊   | 68/100 (68.0%) | ⏳ 02:51<01:14 |  2.33s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.59s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.60s/it

running experiment evaluations |██████▉   | 69/100 (69.0%) | ⏳ 02:54<01:17 |  2.49s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

running experiment evaluations |███████   | 70/100 (70.0%) | ⏳ 02:56<01:10 |  2.34s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

running experiment evaluations |███████   | 71/100 (71.0%) | ⏳ 02:58<01:08 |  2.37s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

running experiment evaluations |███████▏  | 72/100 (72.0%) | ⏳ 03:00<01:02 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

running experiment evaluations |███████▎  | 73/100 (73.0%) | ⏳ 03:02<00:59 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

running experiment evaluations |███████▍  | 74/100 (74.0%) | ⏳ 03:04<00:56 |  2.18s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

running experiment evaluations |███████▌  | 75/100 (75.0%) | ⏳ 03:06<00:52 |  2.10s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it

running experiment evaluations |███████▌  | 76/100 (76.0%) | ⏳ 03:09<00:53 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

running experiment evaluations |███████▋  | 77/100 (77.0%) | ⏳ 03:11<00:48 |  2.11s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

running experiment evaluations |███████▊  | 78/100 (78.0%) | ⏳ 03:13<00:45 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.16s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

running experiment evaluations |███████▉  | 79/100 (79.0%) | ⏳ 03:15<00:45 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.69s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.69s/it

running experiment evaluations |████████  | 80/100 (80.0%) | ⏳ 03:20<01:00 |  3.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.63s/it

running experiment evaluations |████████  | 81/100 (81.0%) | ⏳ 03:23<00:56 |  2.98s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.66s/it

running experiment evaluations |████████▏ | 82/100 (82.0%) | ⏳ 03:25<00:47 |  2.67s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

running experiment evaluations |████████▎ | 83/100 (83.0%) | ⏳ 03:27<00:42 |  2.52s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.50s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.50s/it

running experiment evaluations |████████▍ | 84/100 (84.0%) | ⏳ 03:29<00:36 |  2.29s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

running experiment evaluations |████████▌ | 85/100 (85.0%) | ⏳ 03:31<00:33 |  2.23s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

running experiment evaluations |████████▌ | 86/100 (86.0%) | ⏳ 03:33<00:31 |  2.26s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.09s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.09s/it

running experiment evaluations |████████▋ | 87/100 (87.0%) | ⏳ 03:36<00:29 |  2.28s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

running experiment evaluations |████████▊ | 88/100 (88.0%) | ⏳ 03:38<00:26 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.93s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.93s/it

running experiment evaluations |████████▉ | 89/100 (89.0%) | ⏳ 03:40<00:24 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.97s/it

running experiment evaluations |█████████ | 90/100 (90.0%) | ⏳ 03:42<00:22 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

running experiment evaluations |█████████ | 91/100 (91.0%) | ⏳ 03:44<00:19 |  2.17s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.55s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.55s/it

running experiment evaluations |█████████▏| 92/100 (92.0%) | ⏳ 03:47<00:18 |  2.36s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it

running experiment evaluations |█████████▎| 93/100 (93.0%) | ⏳ 03:49<00:16 |  2.41s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.00s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.00s/it

running experiment evaluations |█████████▍| 94/100 (94.0%) | ⏳ 03:52<00:14 |  2.36s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it

running experiment evaluations |█████████▌| 95/100 (95.0%) | ⏳ 03:54<00:11 |  2.26s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.89s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.90s/it

running experiment evaluations |█████████▌| 96/100 (96.0%) | ⏳ 03:58<00:11 |  2.83s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.26s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.26s/it

running experiment evaluations |█████████▋| 97/100 (97.0%) | ⏳ 04:00<00:08 |  2.74s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.08s/it

running experiment evaluations |█████████▊| 98/100 (98.0%) | ⏳ 04:03<00:05 |  2.62s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.05s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

running experiment evaluations |█████████▉| 99/100 (99.0%) | ⏳ 04:05<00:02 |  2.53s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 04:07<00:00 |  2.42s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 04:07<00:00 |  2.48s/it

  arize.experiments.functions | INFO | ✅ All evaluators completed.

  arize.pre_releases | WARNING | [BETA] experiments.get is a beta API in Arize SDK v8.37.1 and may change without notice. If you experience unexpected failures, please upgrade to the most recent version of the package.

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

columns: ['example_id', 'output', 'error', 'result.trace.id', 'result.trace.timestamp', 'eval.skill_eval.score', 'eval.skill_eval.label', 'eval.skill_eval.explanation', 'eval.skill_eval.trace.id', 'eval.skill_eval.trace.timestamp']
skill-v0 mean score: 0.22

,example_id,output,error,result.trace.id,result.trace.timestamp,eval.skill_eval.score,eval.skill_eval.label,eval.skill_eval.explanation,eval.skill_eval.trace.id,eval.skill_eval.trace.timestamp
0,241fd291-5bb2-4b28-870e-6cc04ca6ba56,"Amanda offered Jerry some cookies she baked, a...",None,4e5b11506557640c9b47c2b864845ad5,1783044038311,1,good,The Generated Summary accurately reflects the ...,54f7bc509255adc5d731916244ffb17d,1783044168701
1,ee4883bf-b95e-4611-9e9f-63db42de45d1,Olivia and Oliver discuss their voting prefere...,None,11a8f3e4b5d7a3a21f8ed2f7e1220436,1783044039717,0,bad,The generated summary accurately reflects the ...,07d2514b9392ca78fbcc397469228e8b,1783044171022
2,c0e644e2-245d-4f11-8c27-767e02a64806,Kim tells Tim she's in a bad mood because she ...,None,4b9bc7629b3f31985a1bc3e9323b1530,1783044040791,0,bad,The Generated Summary provides more detail tha...,a91edf78077dceecb4c3a887aba9f7e1,1783044177781
3,c35f0687-3bc8-4083-bc58-582d57bfcc10,Edward confides to Rachel that he has feelings...,None,75d49215eb1e0cde0fd18b4161252681,1783044042132,0,bad,The Generated Summary introduces the detail th...,bab636f9a74377d240b33bd834abe97c,1783044180041
4,81372906-5f44-4807-bf15-4f1afbf90fa7,Sam tells Naomi he overheard Rick saying he’s ...,None,5c1197e144f66a2e737825435e35804f,1783044043522,0,bad,The Generated Summary accurately reflects the ...,e4f628a77555f8c194b1f372432d573d,1783044182740

In [10]:
filtered_v0 = collect_feedback(eval_v0)
filtered_v0[["output", "eval.skill_eval.label", "eval.skill_eval.explanation"]]

,output,eval.skill_eval.label,eval.skill_eval.explanation
1,Olivia and Oliver discuss their voting prefere...,bad,The generated summary accurately reflects the ...
2,Kim tells Tim she's in a bad mood because she ...,bad,The Generated Summary provides more detail tha...
3,Edward confides to Rachel that he has feelings...,bad,The Generated Summary introduces the detail th...
0,"Amanda offered Jerry some cookies she baked, a...",good,The Generated Summary accurately reflects the ...
5,Neville asks for help remembering his wedding ...,good,The Generated Summary accurately reflects the ...
9,"Matt asked Agnes out on a date, and after some...",good,The Generated Summary accurately reflects the ...
10,"Demi tells Lucas she was promoted, and they ag...",good,The Generated Summary accurately reflects the ...
11,Mark informed George that he has shipped the g...,good,The Generated Summary accurately reflects the ...

In [11]:
from pathlib import Path

def snapshot_skill(version_idx: int) -> str:
    Path(VERSIONS_DIR).mkdir(parents=True, exist_ok=True)
    dest = f"{VERSIONS_DIR}/v{version_idx}.md"
    with open(dest, "w") as f:
        f.write(read_skill())
    return dest

def apply_skill(new_text: str):
    with open(SKILL_PATH, "w") as f:
        f.write(new_text)

In [12]:
meta_prompt = """You are an expert at optimizing Claude "skills" — structured Markdown instruction
files (SKILL.md). You are given the CURRENT SKILL.md and PERFORMANCE DATA from running that skill as
a summarization system prompt over a dialogue dataset. Each record has the model's `output` summary,
an LLM-judge `label` (good/bad) comparing it to a gold reference summary, and an `explanation` of why.

Rewrite the SKILL.md so future summaries earn "good".

CURRENT SKILL.md
================
{current_skill}
================

PERFORMANCE DATA (bad records show failures, good records show what the judge rewards)
================
{feedback_samples}
================

REQUIREMENTS
1. Read every explanation. Find the recurring failure pattern across the `bad` records and contrast
   with the `good` ones.
2. Translate those patterns into GENERAL, REUSABLE instructions — never fixes overfit to specific
   dialogues in the data.
3. Preserve the section structure exactly: Description, Goal, Input, Procedure, Output Format, Rules,
   Quality Checklist. Keep the same Markdown headers.
4. Output ONLY the complete rewritten SKILL.md Markdown. No preamble, no code fences, no commentary.
"""

def _strip_code_fences(text: str) -> str:
    """Defensive: if the model wraps the rewritten SKILL.md in a ``` fence despite the
    instructions, remove it. apply_skill (Task 6) writes this text straight to SKILL.md,
    so a stray fence would silently corrupt the live skill file."""
    t = text.strip()
    if t.startswith("```"):
        lines = t.split("\n")
        lines = lines[1:]  # drop opening fence line (``` or ```markdown)
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]  # drop closing fence line
        t = "\n".join(lines).strip()
    return t

REQUIRED_SKILL_SECTIONS = ["## Description", "## Goal", "## Procedure", "## Rules", "## Quality Checklist"]

def optimize_skill(current_skill: str, filtered_df) -> str:
    feedback = filtered_df[["output", "eval.skill_eval.label", "eval.skill_eval.explanation"]].to_string(index=False)
    raw = gen_chain.invoke(meta_prompt.format(current_skill=current_skill, feedback_samples=feedback))
    text = _strip_code_fences(raw)
    # Guard the actual applied path (not just the Task 5 preview cell): apply_skill writes
    # this straight to the live SKILL.md, so a malformed rewrite would silently corrupt it
    # mid-loop with no other signal.
    for header in REQUIRED_SKILL_SECTIONS:
        assert header in text, f"optimize_skill: missing section {header!r} in rewritten SKILL.md"
    return text

In [13]:
snap = snapshot_skill(0)
new_skill_text = optimize_skill(read_skill(), filtered_v0)
print("snapshotted:", snap)
print("---- proposed SKILL.md ----")
print(new_skill_text)
# optimize_skill() itself now asserts REQUIRED_SKILL_SECTIONS are present (raises if not),
# so reaching this line already confirms the structural check passed.
print("\nOK: all required sections present")

snapshotted: dialog-summary/versions/v0.md
---- proposed SKILL.md ----
# Dialogue Summary Skill

## Description

Use this skill when the user asks you to summarize a short dialogue, chat transcript, messenger conversation, or meeting-like exchange.

## Goal

Create a concise summary that captures the main point of the conversation, including important decisions, requests, plans, or emotional context when relevant.

## Input

The input is usually a speaker-labeled dialogue. Each line may contain a speaker name followed by their message.

Example:

Alice: Are you coming to dinner tonight?
Bob: I might be late because of work.
Alice: That's okay. I'll save you some food.

## Procedure

1. Read the entire dialogue carefully before summarizing.
2. Identify the main participants and ensure their names are transcribed exactly as in the dialogue.
3. Identify the main topic of the conversation.
4. Extract only the most important decisions, requests, plans, problems, or commitments.
5. Exclude greetings, small talk, filler expressions, repeated information, and unnecessary emotional context unless they directly affect the main point or outcome.
6. Avoid adding interpretations, assumptions, or inferred motivations that are not explicitly stated in the dialogue.
7. Write a concise summary in natural language, focusing on the essential facts and outcomes.

## Output Format

Write only the final summary.

The summary should be 1–3 sentences.

## Rules

* Do not add information, interpretations, or motivations that are not explicitly supported by the dialogue.
* Do not confuse or alter who said or wanted what; preserve correct attribution and exact names.
* Include important names, dates, times, places, and commitments as stated.
* Prefer a clear third-person summary.
* Do not quote the dialogue unless the exact wording is crucial to the meaning.
* Be as concise as possible while covering all essential points; omit minor details and excessive elaboration.

## Quality Checklist

Before finalizing, check:

* Does the summary capture only the main point(s) and essential outcomes?
* Are the speakers' intentions and actions represented accurately, without added interpretation?
* Are concrete plans, requests, or decisions included if present?
* Are irrelevant small talk, filler, and unnecessary details removed?
* Are all names, dates, and facts transcribed exactly as in the dialogue?
* Is the summary concise and free of unnecessary elaboration?

OK: all required sections present

## Task 6: Iteration loop + improvement report

Iterate `N_ITERATIONS` times: collect feedback from the last experiment, rewrite `SKILL.md`
with the meta-optimizer, snapshot the pre-edit version to `dialog-summary/versions/`, apply the
new skill, and re-run the experiment as `skill-v{i}`. Finally, report the mean score per version
so the v0→vN improvement is visible (and comparable in the Arize UI).

In [14]:
history = [{"version": "skill-v0", "score": mean_score(eval_v0)}]
last_eval = eval_v0

for i in range(1, N_ITERATIONS + 1):
    filtered = collect_feedback(last_eval)
    new_text = optimize_skill(read_skill(), filtered)
    snapshot_skill(i - 1)          # save the version we are about to replace
    apply_skill(new_text)          # SKILL.md now = optimized version i
    exp, last_eval = run_experiment(f"skill-v{i}")
    score = mean_score(last_eval)
    history.append({"version": f"skill-v{i}", "score": score})
    print(f"skill-v{i} mean score: {score:.3f}")

# Archive the final iteration's skill text too: the loop's snapshot_skill(i-1) calls only
# ever save versions v0..v{N_ITERATIONS-1} (each taken BEFORE that iteration's apply_skill),
# so the skill text produced by the LAST iteration -- the one that earned skill-v{N_ITERATIONS}'s
# score -- was never archived. Without this, versions/ has one fewer file than there are
# experiments, and that prose is unrecoverable once SKILL.md is overwritten again.
snapshot_skill(N_ITERATIONS)

pd.DataFrame(history)

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

  arize.experiments.functions | INFO | 🧪 Experiment started.

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running tasks |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

running tasks |          | 1/100 (1.0%) | ⏳ 00:01<01:49 |  1.11s/it

running tasks |▏         | 2/100 (2.0%) | ⏳ 00:02<01:37 |  1.00it/s

running tasks |▎         | 3/100 (3.0%) | ⏳ 00:03<01:47 |  1.11s/it

running tasks |▍         | 4/100 (4.0%) | ⏳ 00:04<01:42 |  1.07s/it

running tasks |▌         | 5/100 (5.0%) | ⏳ 00:05<01:43 |  1.08s/it

running tasks |▌         | 6/100 (6.0%) | ⏳ 00:06<01:57 |  1.25s/it

running tasks |▋         | 7/100 (7.0%) | ⏳ 00:08<02:06 |  1.36s/it

running tasks |▊         | 8/100 (8.0%) | ⏳ 00:09<01:55 |  1.26s/it

running tasks |▉         | 9/100 (9.0%) | ⏳ 00:11<02:25 |  1.60s/it

running tasks |█         | 10/100 (10.0%) | ⏳ 00:13<02:17 |  1.52s/it

running tasks |█         | 11/100 (11.0%) | ⏳ 00:14<02:00 |  1.35s/it

running tasks |█▏        | 12/100 (12.0%) | ⏳ 00:15<01:52 |  1.28s/it

running tasks |█▎        | 13/100 (13.0%) | ⏳ 00:16<01:42 |  1.18s/it

running tasks |█▍        | 14/100 (14.0%) | ⏳ 00:17<01:45 |  1.23s/it

running tasks |█▌        | 15/100 (15.0%) | ⏳ 00:18<01:43 |  1.22s/it

running tasks |█▌        | 16/100 (16.0%) | ⏳ 00:21<02:06 |  1.51s/it

running tasks |█▋        | 17/100 (17.0%) | ⏳ 00:25<03:22 |  2.44s/it

running tasks |█▊        | 18/100 (18.0%) | ⏳ 00:26<02:51 |  2.09s/it

running tasks |█▉        | 19/100 (19.0%) | ⏳ 00:27<02:23 |  1.77s/it

running tasks |██        | 20/100 (20.0%) | ⏳ 00:28<02:02 |  1.53s/it

running tasks |██        | 21/100 (21.0%) | ⏳ 00:31<02:30 |  1.91s/it

running tasks |██▏       | 22/100 (22.0%) | ⏳ 00:33<02:16 |  1.76s/it

running tasks |██▎       | 23/100 (23.0%) | ⏳ 00:34<01:56 |  1.52s/it

running tasks |██▍       | 24/100 (24.0%) | ⏳ 00:35<01:56 |  1.53s/it

running tasks |██▌       | 25/100 (25.0%) | ⏳ 00:36<01:49 |  1.46s/it

running tasks |██▌       | 26/100 (26.0%) | ⏳ 00:38<01:45 |  1.42s/it

running tasks |██▋       | 27/100 (27.0%) | ⏳ 00:39<01:38 |  1.34s/it

running tasks |██▊       | 28/100 (28.0%) | ⏳ 00:40<01:39 |  1.38s/it

running tasks |██▉       | 29/100 (29.0%) | ⏳ 00:42<01:49 |  1.54s/it

running tasks |███       | 30/100 (30.0%) | ⏳ 00:44<01:47 |  1.54s/it

running tasks |███       | 31/100 (31.0%) | ⏳ 00:45<01:43 |  1.50s/it

running tasks |███▏      | 32/100 (32.0%) | ⏳ 00:46<01:31 |  1.34s/it

running tasks |███▎      | 33/100 (33.0%) | ⏳ 00:52<02:52 |  2.58s/it

running tasks |███▍      | 34/100 (34.0%) | ⏳ 00:53<02:27 |  2.24s/it

running tasks |███▌      | 35/100 (35.0%) | ⏳ 00:54<02:01 |  1.87s/it

running tasks |███▌      | 36/100 (36.0%) | ⏳ 00:56<02:00 |  1.88s/it

running tasks |███▋      | 37/100 (37.0%) | ⏳ 00:57<01:47 |  1.71s/it

running tasks |███▊      | 38/100 (38.0%) | ⏳ 00:58<01:33 |  1.50s/it

running tasks |███▉      | 39/100 (39.0%) | ⏳ 01:00<01:29 |  1.47s/it

running tasks |████      | 40/100 (40.0%) | ⏳ 01:01<01:23 |  1.40s/it

running tasks |████      | 41/100 (41.0%) | ⏳ 01:02<01:21 |  1.39s/it

running tasks |████▏     | 42/100 (42.0%) | ⏳ 01:04<01:22 |  1.42s/it

running tasks |████▎     | 43/100 (43.0%) | ⏳ 01:05<01:24 |  1.48s/it

running tasks |████▍     | 44/100 (44.0%) | ⏳ 01:07<01:23 |  1.50s/it

running tasks |████▌     | 45/100 (45.0%) | ⏳ 01:09<01:24 |  1.53s/it

running tasks |████▌     | 46/100 (46.0%) | ⏳ 01:10<01:17 |  1.44s/it

running tasks |████▋     | 47/100 (47.0%) | ⏳ 01:11<01:11 |  1.35s/it

running tasks |████▊     | 48/100 (48.0%) | ⏳ 01:12<01:11 |  1.37s/it

running tasks |████▉     | 49/100 (49.0%) | ⏳ 01:14<01:09 |  1.36s/it

running tasks |█████     | 50/100 (50.0%) | ⏳ 01:15<01:12 |  1.44s/it

running tasks |█████     | 51/100 (51.0%) | ⏳ 01:16<01:03 |  1.30s/it

running tasks |█████▏    | 52/100 (52.0%) | ⏳ 01:18<01:02 |  1.31s/it

running tasks |█████▎    | 53/100 (53.0%) | ⏳ 01:19<00:59 |  1.28s/it

running tasks |█████▍    | 54/100 (54.0%) | ⏳ 01:20<00:59 |  1.29s/it

running tasks |█████▌    | 55/100 (55.0%) | ⏳ 01:21<00:56 |  1.25s/it

running tasks |█████▌    | 56/100 (56.0%) | ⏳ 01:23<00:54 |  1.25s/it

running tasks |█████▋    | 57/100 (57.0%) | ⏳ 01:24<01:00 |  1.40s/it

running tasks |█████▊    | 58/100 (58.0%) | ⏳ 01:26<00:59 |  1.41s/it

running tasks |█████▉    | 59/100 (59.0%) | ⏳ 01:27<00:56 |  1.39s/it

running tasks |██████    | 60/100 (60.0%) | ⏳ 01:28<00:54 |  1.35s/it

running tasks |██████    | 61/100 (61.0%) | ⏳ 01:30<00:51 |  1.32s/it

running tasks |██████▏   | 62/100 (62.0%) | ⏳ 01:34<01:28 |  2.32s/it

running tasks |██████▎   | 63/100 (63.0%) | ⏳ 01:35<01:12 |  1.96s/it

running tasks |██████▍   | 64/100 (64.0%) | ⏳ 01:37<01:05 |  1.81s/it

running tasks |██████▌   | 65/100 (65.0%) | ⏳ 01:38<00:58 |  1.66s/it

running tasks |██████▌   | 66/100 (66.0%) | ⏳ 01:39<00:49 |  1.45s/it

running tasks |██████▋   | 67/100 (67.0%) | ⏳ 01:41<00:47 |  1.45s/it

running tasks |██████▊   | 68/100 (68.0%) | ⏳ 01:42<00:43 |  1.35s/it

running tasks |██████▉   | 69/100 (69.0%) | ⏳ 01:43<00:39 |  1.27s/it

running tasks |███████   | 70/100 (70.0%) | ⏳ 01:44<00:35 |  1.19s/it

running tasks |███████   | 71/100 (71.0%) | ⏳ 01:45<00:36 |  1.24s/it

running tasks |███████▏  | 72/100 (72.0%) | ⏳ 01:46<00:34 |  1.22s/it

running tasks |███████▎  | 73/100 (73.0%) | ⏳ 01:47<00:32 |  1.21s/it

running tasks |███████▍  | 74/100 (74.0%) | ⏳ 01:49<00:31 |  1.20s/it

running tasks |███████▌  | 75/100 (75.0%) | ⏳ 01:50<00:29 |  1.19s/it

running tasks |███████▌  | 76/100 (76.0%) | ⏳ 01:51<00:28 |  1.19s/it

running tasks |███████▋  | 77/100 (77.0%) | ⏳ 01:53<00:29 |  1.29s/it

running tasks |███████▊  | 78/100 (78.0%) | ⏳ 01:54<00:27 |  1.23s/it

running tasks |███████▉  | 79/100 (79.0%) | ⏳ 01:55<00:24 |  1.15s/it

running tasks |████████  | 80/100 (80.0%) | ⏳ 01:56<00:23 |  1.19s/it

running tasks |████████  | 81/100 (81.0%) | ⏳ 02:02<00:48 |  2.57s/it

running tasks |████████▏ | 82/100 (82.0%) | ⏳ 02:03<00:37 |  2.10s/it

running tasks |████████▎ | 83/100 (83.0%) | ⏳ 02:04<00:29 |  1.76s/it

running tasks |████████▍ | 84/100 (84.0%) | ⏳ 02:05<00:25 |  1.59s/it

running tasks |████████▌ | 85/100 (85.0%) | ⏳ 02:06<00:22 |  1.52s/it

running tasks |████████▌ | 86/100 (86.0%) | ⏳ 02:08<00:20 |  1.49s/it

running tasks |████████▋ | 87/100 (87.0%) | ⏳ 02:09<00:17 |  1.37s/it

running tasks |████████▊ | 88/100 (88.0%) | ⏳ 02:10<00:15 |  1.32s/it

running tasks |████████▉ | 89/100 (89.0%) | ⏳ 02:12<00:16 |  1.46s/it

running tasks |█████████ | 90/100 (90.0%) | ⏳ 02:13<00:13 |  1.36s/it

running tasks |█████████ | 91/100 (91.0%) | ⏳ 02:14<00:11 |  1.23s/it

running tasks |█████████▏| 92/100 (92.0%) | ⏳ 02:15<00:09 |  1.19s/it

running tasks |█████████▎| 93/100 (93.0%) | ⏳ 02:16<00:08 |  1.21s/it

running tasks |█████████▍| 94/100 (94.0%) | ⏳ 02:17<00:07 |  1.19s/it

running tasks |█████████▌| 95/100 (95.0%) | ⏳ 02:18<00:05 |  1.15s/it

running tasks |█████████▌| 96/100 (96.0%) | ⏳ 02:19<00:04 |  1.14s/it

running tasks |█████████▋| 97/100 (97.0%) | ⏳ 02:21<00:03 |  1.25s/it

running tasks |█████████▊| 98/100 (98.0%) | ⏳ 02:22<00:02 |  1.24s/it

running tasks |█████████▉| 99/100 (99.0%) | ⏳ 02:23<00:01 |  1.21s/it

running tasks |██████████| 100/100 (100.0%) | ⏳ 02:25<00:00 |  1.24s/it

running tasks |██████████| 100/100 (100.0%) | ⏳ 02:25<00:00 |  1.45s/it

  arize.experiments.functions | INFO | ✅ Task runs completed.
Tasks Summary (07/03/26 11:09 AM +0900)
---------------------------------------
   n_examples  n_runs  n_errors
0         100     100         0

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running experiment evaluations |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.47s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.47s/it

running experiment evaluations |          | 1/100 (1.0%) | ⏳ 00:01<02:50 |  1.72s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.37s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.37s/it

running experiment evaluations |▏         | 2/100 (2.0%) | ⏳ 00:03<02:43 |  1.67s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it

running experiment evaluations |▎         | 3/100 (3.0%) | ⏳ 00:05<02:55 |  1.81s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

running experiment evaluations |▍         | 4/100 (4.0%) | ⏳ 00:07<03:00 |  1.88s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.66s/it

running experiment evaluations |▌         | 5/100 (5.0%) | ⏳ 00:09<03:01 |  1.91s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.63s/it

running experiment evaluations |▌         | 6/100 (6.0%) | ⏳ 00:11<02:58 |  1.90s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:08<00:00 |  8.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:08<00:00 |  8.57s/it

running experiment evaluations |▋         | 7/100 (7.0%) | ⏳ 00:20<06:27 |  4.17s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

running experiment evaluations |▊         | 8/100 (8.0%) | ⏳ 00:22<05:24 |  3.53s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

running experiment evaluations |▉         | 9/100 (9.0%) | ⏳ 00:24<04:53 |  3.23s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

running experiment evaluations |█         | 10/100 (10.0%) | ⏳ 00:27<04:31 |  3.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.26s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.26s/it

running experiment evaluations |█         | 11/100 (11.0%) | ⏳ 00:28<03:47 |  2.56s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.27s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.27s/it

running experiment evaluations |█▏        | 12/100 (12.0%) | ⏳ 00:30<03:17 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

running experiment evaluations |█▎        | 13/100 (13.0%) | ⏳ 00:32<03:05 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

running experiment evaluations |█▍        | 14/100 (14.0%) | ⏳ 00:34<03:04 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

running experiment evaluations |█▌        | 15/100 (15.0%) | ⏳ 00:36<03:07 |  2.20s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.62s/it

running experiment evaluations |█▌        | 16/100 (16.0%) | ⏳ 00:39<03:22 |  2.41s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it

running experiment evaluations |█▋        | 17/100 (17.0%) | ⏳ 00:41<03:05 |  2.24s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.55s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.55s/it

running experiment evaluations |█▊        | 18/100 (18.0%) | ⏳ 00:45<03:42 |  2.71s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it

running experiment evaluations |█▉        | 19/100 (19.0%) | ⏳ 00:47<03:17 |  2.44s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

running experiment evaluations |██        | 20/100 (20.0%) | ⏳ 00:49<03:03 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

running experiment evaluations |██        | 21/100 (21.0%) | ⏳ 00:51<02:59 |  2.28s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

running experiment evaluations |██▏       | 22/100 (22.0%) | ⏳ 00:53<02:48 |  2.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.37s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.37s/it

running experiment evaluations |██▎       | 23/100 (23.0%) | ⏳ 00:55<02:57 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.09s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.09s/it

running experiment evaluations |██▍       | 24/100 (24.0%) | ⏳ 00:58<02:56 |  2.32s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.26s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.26s/it

running experiment evaluations |██▌       | 25/100 (25.0%) | ⏳ 01:00<02:58 |  2.38s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.15s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.15s/it

running experiment evaluations |██▌       | 26/100 (26.0%) | ⏳ 01:03<02:56 |  2.39s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.55s/it

running experiment evaluations |██▋       | 27/100 (27.0%) | ⏳ 01:04<02:41 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

running experiment evaluations |██▊       | 28/100 (28.0%) | ⏳ 01:07<02:43 |  2.27s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.67s/it

running experiment evaluations |██▉       | 29/100 (29.0%) | ⏳ 01:10<02:55 |  2.47s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.49s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.49s/it

running experiment evaluations |███       | 30/100 (30.0%) | ⏳ 01:11<02:37 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

running experiment evaluations |███       | 31/100 (31.0%) | ⏳ 01:14<02:34 |  2.24s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

running experiment evaluations |███▏      | 32/100 (32.0%) | ⏳ 01:16<02:26 |  2.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

running experiment evaluations |███▎      | 33/100 (33.0%) | ⏳ 01:18<02:26 |  2.18s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

running experiment evaluations |███▍      | 34/100 (34.0%) | ⏳ 01:20<02:26 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.93s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.93s/it

running experiment evaluations |███▌      | 35/100 (35.0%) | ⏳ 01:22<02:24 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

running experiment evaluations |███▌      | 36/100 (36.0%) | ⏳ 01:25<02:20 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

running experiment evaluations |███▋      | 37/100 (37.0%) | ⏳ 01:27<02:15 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.37s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

running experiment evaluations |███▊      | 38/100 (38.0%) | ⏳ 01:28<02:03 |  1.99s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.30s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.30s/it

running experiment evaluations |███▉      | 39/100 (39.0%) | ⏳ 01:30<01:53 |  1.86s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

running experiment evaluations |████      | 40/100 (40.0%) | ⏳ 01:32<01:52 |  1.88s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

running experiment evaluations |████      | 41/100 (41.0%) | ⏳ 01:34<01:56 |  1.98s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.91s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.92s/it

running experiment evaluations |████▏     | 42/100 (42.0%) | ⏳ 01:37<02:15 |  2.34s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.02s/it

running experiment evaluations |████▎     | 43/100 (43.0%) | ⏳ 01:39<02:12 |  2.32s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

running experiment evaluations |████▍     | 44/100 (44.0%) | ⏳ 01:42<02:10 |  2.34s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.79s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

running experiment evaluations |████▌     | 45/100 (45.0%) | ⏳ 01:44<02:03 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.03s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.04s/it

running experiment evaluations |████▌     | 46/100 (46.0%) | ⏳ 01:46<02:02 |  2.27s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.76s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.76s/it

running experiment evaluations |████▋     | 47/100 (47.0%) | ⏳ 01:48<01:56 |  2.20s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

running experiment evaluations |████▊     | 48/100 (48.0%) | ⏳ 01:50<01:50 |  2.13s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.27s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.27s/it

running experiment evaluations |████▉     | 49/100 (49.0%) | ⏳ 01:52<01:39 |  1.95s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

running experiment evaluations |█████     | 50/100 (50.0%) | ⏳ 01:54<01:41 |  2.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it

running experiment evaluations |█████     | 51/100 (51.0%) | ⏳ 01:56<01:37 |  2.00s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

running experiment evaluations |█████▏    | 52/100 (52.0%) | ⏳ 01:58<01:36 |  2.01s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.41s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.41s/it

running experiment evaluations |█████▎    | 53/100 (53.0%) | ⏳ 02:00<01:43 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.81s/it

running experiment evaluations |█████▍    | 54/100 (54.0%) | ⏳ 02:03<01:39 |  2.17s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.54s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.55s/it

running experiment evaluations |█████▌    | 55/100 (55.0%) | ⏳ 02:05<01:46 |  2.36s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.93s/it

running experiment evaluations |█████▌    | 56/100 (56.0%) | ⏳ 02:08<01:41 |  2.31s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.15s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.15s/it

running experiment evaluations |█████▋    | 57/100 (57.0%) | ⏳ 02:10<01:40 |  2.34s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

running experiment evaluations |█████▊    | 58/100 (58.0%) | ⏳ 02:12<01:31 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

running experiment evaluations |█████▉    | 59/100 (59.0%) | ⏳ 02:14<01:30 |  2.20s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

running experiment evaluations |██████    | 60/100 (60.0%) | ⏳ 02:16<01:29 |  2.24s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

running experiment evaluations |██████    | 61/100 (61.0%) | ⏳ 02:19<01:29 |  2.31s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

running experiment evaluations |██████▏   | 62/100 (62.0%) | ⏳ 02:21<01:26 |  2.29s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

running experiment evaluations |██████▎   | 63/100 (63.0%) | ⏳ 02:23<01:20 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

running experiment evaluations |██████▍   | 64/100 (64.0%) | ⏳ 02:25<01:18 |  2.18s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.35s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.35s/it

running experiment evaluations |██████▌   | 65/100 (65.0%) | ⏳ 02:28<01:20 |  2.31s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

running experiment evaluations |██████▌   | 66/100 (66.0%) | ⏳ 02:30<01:14 |  2.18s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

running experiment evaluations |██████▋   | 67/100 (67.0%) | ⏳ 02:32<01:12 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.34s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.35s/it

running experiment evaluations |██████▊   | 68/100 (68.0%) | ⏳ 02:33<01:04 |  2.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

running experiment evaluations |██████▉   | 69/100 (69.0%) | ⏳ 02:35<01:02 |  2.01s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.02s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.02s/it

running experiment evaluations |███████   | 70/100 (70.0%) | ⏳ 02:38<01:03 |  2.12s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

running experiment evaluations |███████   | 71/100 (71.0%) | ⏳ 02:40<00:58 |  2.03s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

running experiment evaluations |███████▏  | 72/100 (72.0%) | ⏳ 02:42<00:57 |  2.04s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.73s/it

running experiment evaluations |███████▎  | 73/100 (73.0%) | ⏳ 02:44<00:55 |  2.06s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.91s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.92s/it

running experiment evaluations |███████▍  | 74/100 (74.0%) | ⏳ 02:47<01:02 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.49s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.50s/it

running experiment evaluations |███████▌  | 75/100 (75.0%) | ⏳ 02:50<01:02 |  2.51s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.67s/it

running experiment evaluations |███████▌  | 76/100 (76.0%) | ⏳ 02:54<01:10 |  2.93s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.56s/it

running experiment evaluations |███████▋  | 77/100 (77.0%) | ⏳ 02:57<01:06 |  2.90s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

running experiment evaluations |███████▊  | 78/100 (78.0%) | ⏳ 02:59<00:57 |  2.63s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

running experiment evaluations |███████▉  | 79/100 (79.0%) | ⏳ 03:00<00:49 |  2.38s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

running experiment evaluations |████████  | 80/100 (80.0%) | ⏳ 03:03<00:48 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.78s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.78s/it

running experiment evaluations |████████  | 81/100 (81.0%) | ⏳ 03:06<00:49 |  2.60s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it

running experiment evaluations |████████▏ | 82/100 (82.0%) | ⏳ 03:08<00:43 |  2.41s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.40s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.40s/it

running experiment evaluations |████████▎ | 83/100 (83.0%) | ⏳ 03:12<00:47 |  2.79s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.47s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.47s/it

running experiment evaluations |████████▍ | 84/100 (84.0%) | ⏳ 03:13<00:39 |  2.47s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it

running experiment evaluations |████████▌ | 85/100 (85.0%) | ⏳ 03:15<00:34 |  2.27s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

running experiment evaluations |████████▌ | 86/100 (86.0%) | ⏳ 03:17<00:32 |  2.29s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

running experiment evaluations |████████▋ | 87/100 (87.0%) | ⏳ 03:19<00:27 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.37s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.37s/it

running experiment evaluations |████████▊ | 88/100 (88.0%) | ⏳ 03:22<00:27 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.75s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.75s/it

running experiment evaluations |████████▉ | 89/100 (89.0%) | ⏳ 03:25<00:27 |  2.51s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.79s/it

running experiment evaluations |█████████ | 90/100 (90.0%) | ⏳ 03:27<00:23 |  2.37s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.39s/it

running experiment evaluations |█████████ | 91/100 (91.0%) | ⏳ 03:29<00:19 |  2.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.18s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.19s/it

running experiment evaluations |█████████▏| 92/100 (92.0%) | ⏳ 03:31<00:17 |  2.24s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.33s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.33s/it

running experiment evaluations |█████████▎| 93/100 (93.0%) | ⏳ 03:33<00:14 |  2.05s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.30s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.30s/it

running experiment evaluations |█████████▍| 94/100 (94.0%) | ⏳ 03:37<00:16 |  2.80s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

running experiment evaluations |█████████▌| 95/100 (95.0%) | ⏳ 03:39<00:12 |  2.53s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.03s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.03s/it

running experiment evaluations |█████████▌| 96/100 (96.0%) | ⏳ 03:42<00:11 |  2.76s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.74s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.74s/it

running experiment evaluations |█████████▋| 97/100 (97.0%) | ⏳ 03:46<00:09 |  3.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it

running experiment evaluations |█████████▊| 98/100 (98.0%) | ⏳ 03:48<00:05 |  2.73s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.23s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.23s/it

running experiment evaluations |█████████▉| 99/100 (99.0%) | ⏳ 03:51<00:02 |  2.66s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.12s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.12s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 03:52<00:00 |  2.28s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 03:52<00:00 |  2.33s/it

  arize.experiments.functions | INFO | ✅ All evaluators completed.

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

skill-v1 mean score: 0.230

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

  arize.experiments.functions | INFO | 🧪 Experiment started.

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running tasks |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

running tasks |          | 1/100 (1.0%) | ⏳ 00:01<01:43 |  1.04s/it

running tasks |▏         | 2/100 (2.0%) | ⏳ 00:01<01:34 |  1.04it/s

running tasks |▎         | 3/100 (3.0%) | ⏳ 00:02<01:36 |  1.01it/s

running tasks |▍         | 4/100 (4.0%) | ⏳ 00:04<01:37 |  1.02s/it

running tasks |▌         | 5/100 (5.0%) | ⏳ 00:05<01:41 |  1.07s/it

running tasks |▌         | 6/100 (6.0%) | ⏳ 00:06<01:37 |  1.03s/it

running tasks |▋         | 7/100 (7.0%) | ⏳ 00:07<01:40 |  1.08s/it

running tasks |▊         | 8/100 (8.0%) | ⏳ 00:08<01:39 |  1.08s/it

running tasks |▉         | 9/100 (9.0%) | ⏳ 00:09<01:36 |  1.07s/it

running tasks |█         | 10/100 (10.0%) | ⏳ 00:10<01:38 |  1.09s/it

running tasks |█         | 11/100 (11.0%) | ⏳ 00:11<01:31 |  1.03s/it

running tasks |█▏        | 12/100 (12.0%) | ⏳ 00:13<01:51 |  1.27s/it

running tasks |█▎        | 13/100 (13.0%) | ⏳ 00:14<01:43 |  1.19s/it

running tasks |█▍        | 14/100 (14.0%) | ⏳ 00:15<01:44 |  1.21s/it

running tasks |█▌        | 15/100 (15.0%) | ⏳ 00:16<01:38 |  1.16s/it

running tasks |█▌        | 16/100 (16.0%) | ⏳ 00:17<01:38 |  1.17s/it

running tasks |█▋        | 17/100 (17.0%) | ⏳ 00:19<01:41 |  1.22s/it

running tasks |█▊        | 18/100 (18.0%) | ⏳ 00:20<01:35 |  1.16s/it

running tasks |█▉        | 19/100 (19.0%) | ⏳ 00:21<01:33 |  1.15s/it

running tasks |██        | 20/100 (20.0%) | ⏳ 00:22<01:27 |  1.10s/it

running tasks |██        | 21/100 (21.0%) | ⏳ 00:23<01:24 |  1.07s/it

running tasks |██▏       | 22/100 (22.0%) | ⏳ 00:24<01:23 |  1.06s/it

running tasks |██▎       | 23/100 (23.0%) | ⏳ 00:25<01:18 |  1.02s/it

running tasks |██▍       | 24/100 (24.0%) | ⏳ 00:27<01:34 |  1.24s/it

running tasks |██▌       | 25/100 (25.0%) | ⏳ 00:28<01:30 |  1.21s/it

running tasks |██▌       | 26/100 (26.0%) | ⏳ 00:29<01:28 |  1.19s/it

running tasks |██▋       | 27/100 (27.0%) | ⏳ 00:30<01:21 |  1.12s/it

running tasks |██▊       | 28/100 (28.0%) | ⏳ 00:31<01:20 |  1.12s/it

running tasks |██▉       | 29/100 (29.0%) | ⏳ 00:32<01:29 |  1.27s/it

running tasks |███       | 30/100 (30.0%) | ⏳ 00:34<01:28 |  1.26s/it

running tasks |███       | 31/100 (31.0%) | ⏳ 00:35<01:24 |  1.23s/it

running tasks |███▏      | 32/100 (32.0%) | ⏳ 00:36<01:17 |  1.14s/it

running tasks |███▎      | 33/100 (33.0%) | ⏳ 00:37<01:11 |  1.07s/it

running tasks |███▍      | 34/100 (34.0%) | ⏳ 00:38<01:21 |  1.23s/it

running tasks |███▌      | 35/100 (35.0%) | ⏳ 00:39<01:16 |  1.18s/it

running tasks |███▌      | 36/100 (36.0%) | ⏳ 00:41<01:25 |  1.33s/it

running tasks |███▋      | 37/100 (37.0%) | ⏳ 00:42<01:18 |  1.25s/it

running tasks |███▊      | 38/100 (38.0%) | ⏳ 00:43<01:14 |  1.20s/it

running tasks |███▉      | 39/100 (39.0%) | ⏳ 00:44<01:11 |  1.17s/it

running tasks |████      | 40/100 (40.0%) | ⏳ 00:46<01:12 |  1.21s/it

running tasks |████      | 41/100 (41.0%) | ⏳ 00:47<01:09 |  1.18s/it

running tasks |████▏     | 42/100 (42.0%) | ⏳ 00:48<01:08 |  1.18s/it

running tasks |████▎     | 43/100 (43.0%) | ⏳ 00:49<01:12 |  1.26s/it

running tasks |████▍     | 44/100 (44.0%) | ⏳ 00:51<01:08 |  1.23s/it

running tasks |████▌     | 45/100 (45.0%) | ⏳ 00:52<01:06 |  1.21s/it

running tasks |████▌     | 46/100 (46.0%) | ⏳ 00:53<01:02 |  1.17s/it

running tasks |████▋     | 47/100 (47.0%) | ⏳ 00:54<01:00 |  1.14s/it

running tasks |████▊     | 48/100 (48.0%) | ⏳ 00:55<01:02 |  1.21s/it

running tasks |████▉     | 49/100 (49.0%) | ⏳ 00:56<00:58 |  1.15s/it

running tasks |█████     | 50/100 (50.0%) | ⏳ 00:57<00:59 |  1.18s/it

running tasks |█████     | 51/100 (51.0%) | ⏳ 00:59<00:57 |  1.18s/it

running tasks |█████▏    | 52/100 (52.0%) | ⏳ 01:00<00:59 |  1.23s/it

running tasks |█████▎    | 53/100 (53.0%) | ⏳ 01:01<00:58 |  1.25s/it

running tasks |█████▍    | 54/100 (54.0%) | ⏳ 01:04<01:12 |  1.59s/it

running tasks |█████▌    | 55/100 (55.0%) | ⏳ 01:06<01:18 |  1.75s/it

running tasks |█████▌    | 56/100 (56.0%) | ⏳ 01:07<01:15 |  1.72s/it

running tasks |█████▋    | 57/100 (57.0%) | ⏳ 01:09<01:11 |  1.67s/it

running tasks |█████▊    | 58/100 (58.0%) | ⏳ 01:11<01:13 |  1.75s/it

running tasks |█████▉    | 59/100 (59.0%) | ⏳ 01:12<01:04 |  1.58s/it

running tasks |██████    | 60/100 (60.0%) | ⏳ 01:14<01:08 |  1.70s/it

running tasks |██████    | 61/100 (61.0%) | ⏳ 01:16<01:10 |  1.81s/it

running tasks |██████▏   | 62/100 (62.0%) | ⏳ 01:17<01:02 |  1.63s/it

running tasks |██████▎   | 63/100 (63.0%) | ⏳ 01:18<00:52 |  1.42s/it

running tasks |██████▍   | 64/100 (64.0%) | ⏳ 01:19<00:48 |  1.34s/it

running tasks |██████▌   | 65/100 (65.0%) | ⏳ 01:20<00:42 |  1.21s/it

running tasks |██████▌   | 66/100 (66.0%) | ⏳ 01:21<00:36 |  1.09s/it

running tasks |██████▋   | 67/100 (67.0%) | ⏳ 01:22<00:34 |  1.04s/it

running tasks |██████▊   | 68/100 (68.0%) | ⏳ 01:23<00:33 |  1.06s/it

running tasks |██████▉   | 69/100 (69.0%) | ⏳ 01:24<00:31 |  1.03s/it

running tasks |███████   | 70/100 (70.0%) | ⏳ 01:25<00:29 |  1.01it/s

running tasks |███████   | 71/100 (71.0%) | ⏳ 01:26<00:26 |  1.08it/s

running tasks |███████▏  | 72/100 (72.0%) | ⏳ 01:29<00:47 |  1.71s/it

running tasks |███████▎  | 73/100 (73.0%) | ⏳ 01:31<00:45 |  1.68s/it

running tasks |███████▍  | 74/100 (74.0%) | ⏳ 01:32<00:39 |  1.51s/it

running tasks |███████▌  | 75/100 (75.0%) | ⏳ 01:33<00:35 |  1.41s/it

running tasks |███████▌  | 76/100 (76.0%) | ⏳ 01:34<00:31 |  1.31s/it

running tasks |███████▋  | 77/100 (77.0%) | ⏳ 01:36<00:29 |  1.29s/it

running tasks |███████▊  | 78/100 (78.0%) | ⏳ 01:37<00:26 |  1.22s/it

running tasks |███████▉  | 79/100 (79.0%) | ⏳ 01:37<00:23 |  1.11s/it

running tasks |████████  | 80/100 (80.0%) | ⏳ 01:39<00:21 |  1.09s/it

running tasks |████████  | 81/100 (81.0%) | ⏳ 01:41<00:30 |  1.61s/it

running tasks |████████▏ | 82/100 (82.0%) | ⏳ 01:43<00:27 |  1.51s/it

running tasks |████████▎ | 83/100 (83.0%) | ⏳ 01:44<00:22 |  1.35s/it

running tasks |████████▍ | 84/100 (84.0%) | ⏳ 01:45<00:20 |  1.25s/it

running tasks |████████▌ | 85/100 (85.0%) | ⏳ 01:46<00:17 |  1.17s/it

running tasks |████████▌ | 86/100 (86.0%) | ⏳ 01:47<00:16 |  1.18s/it

running tasks |████████▋ | 87/100 (87.0%) | ⏳ 01:48<00:15 |  1.23s/it

running tasks |████████▊ | 88/100 (88.0%) | ⏳ 01:49<00:13 |  1.15s/it

running tasks |████████▉ | 89/100 (89.0%) | ⏳ 01:51<00:13 |  1.23s/it

running tasks |█████████ | 90/100 (90.0%) | ⏳ 01:52<00:12 |  1.20s/it

running tasks |█████████ | 91/100 (91.0%) | ⏳ 01:53<00:10 |  1.17s/it

running tasks |█████████▏| 92/100 (92.0%) | ⏳ 01:54<00:09 |  1.15s/it

running tasks |█████████▎| 93/100 (93.0%) | ⏳ 01:55<00:07 |  1.07s/it

running tasks |█████████▍| 94/100 (94.0%) | ⏳ 01:56<00:06 |  1.01s/it

running tasks |█████████▌| 95/100 (95.0%) | ⏳ 01:57<00:05 |  1.18s/it

running tasks |█████████▌| 96/100 (96.0%) | ⏳ 01:58<00:04 |  1.17s/it

running tasks |█████████▋| 97/100 (97.0%) | ⏳ 01:59<00:03 |  1.15s/it

running tasks |█████████▊| 98/100 (98.0%) | ⏳ 02:00<00:02 |  1.05s/it

running tasks |█████████▉| 99/100 (99.0%) | ⏳ 02:01<00:01 |  1.03s/it

running tasks |██████████| 100/100 (100.0%) | ⏳ 02:02<00:00 |  1.01s/it

running tasks |██████████| 100/100 (100.0%) | ⏳ 02:02<00:00 |  1.23s/it

  arize.experiments.functions | INFO | ✅ Task runs completed.
Tasks Summary (07/03/26 11:15 AM +0900)
---------------------------------------
   n_examples  n_runs  n_errors
0         100     100         0

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running experiment evaluations |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.23s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.24s/it

running experiment evaluations |          | 1/100 (1.0%) | ⏳ 00:02<04:06 |  2.49s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

running experiment evaluations |▏         | 2/100 (2.0%) | ⏳ 00:04<03:37 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

running experiment evaluations |▎         | 3/100 (3.0%) | ⏳ 00:06<03:46 |  2.33s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.81s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.81s/it

running experiment evaluations |▍         | 4/100 (4.0%) | ⏳ 00:10<04:12 |  2.63s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

running experiment evaluations |▌         | 5/100 (5.0%) | ⏳ 00:12<04:04 |  2.57s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it

running experiment evaluations |▌         | 6/100 (6.0%) | ⏳ 00:15<03:59 |  2.55s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.83s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.83s/it

running experiment evaluations |▋         | 7/100 (7.0%) | ⏳ 00:17<03:43 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

running experiment evaluations |▊         | 8/100 (8.0%) | ⏳ 00:19<03:30 |  2.28s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.43s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.44s/it

running experiment evaluations |▉         | 9/100 (9.0%) | ⏳ 00:21<03:39 |  2.41s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.03s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.03s/it

running experiment evaluations |█         | 10/100 (10.0%) | ⏳ 00:24<03:33 |  2.37s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.54s/it

running experiment evaluations |█         | 11/100 (11.0%) | ⏳ 00:25<03:15 |  2.20s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

running experiment evaluations |█▏        | 12/100 (12.0%) | ⏳ 00:27<03:04 |  2.10s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it

running experiment evaluations |█▎        | 13/100 (13.0%) | ⏳ 00:29<02:57 |  2.04s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.89s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.89s/it

running experiment evaluations |█▍        | 14/100 (14.0%) | ⏳ 00:32<03:24 |  2.38s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

running experiment evaluations |█▌        | 15/100 (15.0%) | ⏳ 00:34<03:02 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

running experiment evaluations |█▌        | 16/100 (16.0%) | ⏳ 00:36<03:02 |  2.17s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.13s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.14s/it

running experiment evaluations |█▋        | 17/100 (17.0%) | ⏳ 00:38<02:40 |  1.94s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it

running experiment evaluations |█▊        | 18/100 (18.0%) | ⏳ 00:40<02:39 |  1.95s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.43s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.43s/it

running experiment evaluations |█▉        | 19/100 (19.0%) | ⏳ 00:41<02:31 |  1.87s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.43s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.43s/it

running experiment evaluations |██        | 20/100 (20.0%) | ⏳ 00:43<02:24 |  1.81s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.46s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.46s/it

running experiment evaluations |██        | 21/100 (21.0%) | ⏳ 00:46<02:44 |  2.08s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

running experiment evaluations |██▏       | 22/100 (22.0%) | ⏳ 00:48<02:42 |  2.08s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

running experiment evaluations |██▎       | 23/100 (23.0%) | ⏳ 00:50<02:46 |  2.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

running experiment evaluations |██▍       | 24/100 (24.0%) | ⏳ 00:53<02:53 |  2.28s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.22s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.22s/it

running experiment evaluations |██▌       | 25/100 (25.0%) | ⏳ 00:54<02:33 |  2.04s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

running experiment evaluations |██▌       | 26/100 (26.0%) | ⏳ 00:56<02:34 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it

running experiment evaluations |██▋       | 27/100 (27.0%) | ⏳ 00:58<02:27 |  2.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.45s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.45s/it

running experiment evaluations |██▊       | 28/100 (28.0%) | ⏳ 01:01<02:40 |  2.23s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.55s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.56s/it

running experiment evaluations |██▉       | 29/100 (29.0%) | ⏳ 01:04<02:50 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.03s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.04s/it

running experiment evaluations |███       | 30/100 (30.0%) | ⏳ 01:06<02:46 |  2.37s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.49s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.49s/it

running experiment evaluations |███       | 31/100 (31.0%) | ⏳ 01:09<02:51 |  2.49s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.13s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.13s/it

running experiment evaluations |███▏      | 32/100 (32.0%) | ⏳ 01:13<03:27 |  3.06s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.40s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.40s/it

running experiment evaluations |███▎      | 33/100 (33.0%) | ⏳ 01:17<03:37 |  3.24s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:06<00:00 |  6.89s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:06<00:00 |  6.89s/it

running experiment evaluations |███▍      | 34/100 (34.0%) | ⏳ 01:24<04:51 |  4.41s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.74s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.74s/it

running experiment evaluations |███▌      | 35/100 (35.0%) | ⏳ 01:26<03:59 |  3.69s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.68s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.68s/it

running experiment evaluations |███▌      | 36/100 (36.0%) | ⏳ 01:31<04:20 |  4.07s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

running experiment evaluations |███▋      | 37/100 (37.0%) | ⏳ 01:33<03:36 |  3.43s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.47s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.48s/it

running experiment evaluations |███▊      | 38/100 (38.0%) | ⏳ 01:35<03:02 |  2.95s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

running experiment evaluations |███▉      | 39/100 (39.0%) | ⏳ 01:37<02:46 |  2.72s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.19s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

running experiment evaluations |████      | 40/100 (40.0%) | ⏳ 01:39<02:38 |  2.65s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.29s/it

running experiment evaluations |████      | 41/100 (41.0%) | ⏳ 01:42<02:34 |  2.62s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

running experiment evaluations |████▏     | 42/100 (42.0%) | ⏳ 01:44<02:19 |  2.41s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.96s/it

running experiment evaluations |████▎     | 43/100 (43.0%) | ⏳ 01:46<02:14 |  2.35s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

running experiment evaluations |████▍     | 44/100 (44.0%) | ⏳ 01:48<02:10 |  2.33s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.66s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it

running experiment evaluations |████▌     | 45/100 (45.0%) | ⏳ 01:50<02:01 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

running experiment evaluations |████▌     | 46/100 (46.0%) | ⏳ 01:52<01:59 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.07s/it

running experiment evaluations |████▋     | 47/100 (47.0%) | ⏳ 01:55<01:59 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.91s/it

running experiment evaluations |████▊     | 48/100 (48.0%) | ⏳ 01:57<01:55 |  2.23s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.02s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.03s/it

running experiment evaluations |████▉     | 49/100 (49.0%) | ⏳ 01:59<01:54 |  2.24s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.47s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.47s/it

running experiment evaluations |█████     | 50/100 (50.0%) | ⏳ 02:01<01:44 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

running experiment evaluations |█████     | 51/100 (51.0%) | ⏳ 02:03<01:45 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it

running experiment evaluations |█████▏    | 52/100 (52.0%) | ⏳ 02:05<01:40 |  2.08s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.99s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.99s/it

running experiment evaluations |█████▎    | 53/100 (53.0%) | ⏳ 02:07<01:40 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.02s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.03s/it

running experiment evaluations |█████▍    | 54/100 (54.0%) | ⏳ 02:10<01:40 |  2.18s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.94s/it

running experiment evaluations |█████▌    | 55/100 (55.0%) | ⏳ 02:12<01:38 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

running experiment evaluations |█████▌    | 56/100 (56.0%) | ⏳ 02:14<01:31 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.98s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.98s/it

running experiment evaluations |█████▋    | 57/100 (57.0%) | ⏳ 02:16<01:31 |  2.13s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.79s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.79s/it

running experiment evaluations |█████▊    | 58/100 (58.0%) | ⏳ 02:18<01:28 |  2.11s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.12s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.12s/it

running experiment evaluations |█████▉    | 59/100 (59.0%) | ⏳ 02:20<01:29 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.75s/it

running experiment evaluations |██████    | 60/100 (60.0%) | ⏳ 02:22<01:25 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it

running experiment evaluations |██████    | 61/100 (61.0%) | ⏳ 02:24<01:20 |  2.06s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.45s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.45s/it

running experiment evaluations |██████▏   | 62/100 (62.0%) | ⏳ 02:27<01:25 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.99s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.99s/it

running experiment evaluations |██████▎   | 63/100 (63.0%) | ⏳ 02:29<01:23 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.89s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.89s/it

running experiment evaluations |██████▍   | 64/100 (64.0%) | ⏳ 02:31<01:20 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it

running experiment evaluations |██████▌   | 65/100 (65.0%) | ⏳ 02:33<01:13 |  2.11s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

running experiment evaluations |██████▌   | 66/100 (66.0%) | ⏳ 02:35<01:08 |  2.03s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it

running experiment evaluations |██████▋   | 67/100 (67.0%) | ⏳ 02:37<01:06 |  2.00s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.02s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.02s/it

running experiment evaluations |██████▊   | 68/100 (68.0%) | ⏳ 02:39<01:06 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

running experiment evaluations |██████▉   | 69/100 (69.0%) | ⏳ 02:41<01:04 |  2.08s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.48s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.48s/it

running experiment evaluations |███████   | 70/100 (70.0%) | ⏳ 02:43<00:59 |  1.98s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.00s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

running experiment evaluations |███████   | 71/100 (71.0%) | ⏳ 02:45<00:59 |  2.07s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.30s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.30s/it

running experiment evaluations |███████▏  | 72/100 (72.0%) | ⏳ 02:48<01:02 |  2.22s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.74s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.74s/it

running experiment evaluations |███████▎  | 73/100 (73.0%) | ⏳ 02:50<00:58 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

running experiment evaluations |███████▍  | 74/100 (74.0%) | ⏳ 02:52<00:54 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

running experiment evaluations |███████▌  | 75/100 (75.0%) | ⏳ 02:54<00:52 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

running experiment evaluations |███████▌  | 76/100 (76.0%) | ⏳ 02:56<00:50 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

running experiment evaluations |███████▋  | 77/100 (77.0%) | ⏳ 02:58<00:48 |  2.11s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.57s/it

running experiment evaluations |███████▊  | 78/100 (78.0%) | ⏳ 03:01<00:51 |  2.33s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.35s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.36s/it

running experiment evaluations |███████▉  | 79/100 (79.0%) | ⏳ 03:03<00:44 |  2.11s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.40s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.40s/it

running experiment evaluations |████████  | 80/100 (80.0%) | ⏳ 03:04<00:39 |  1.98s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.52s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.52s/it

running experiment evaluations |████████  | 81/100 (81.0%) | ⏳ 03:08<00:47 |  2.52s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.51s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.51s/it

running experiment evaluations |████████▏ | 82/100 (82.0%) | ⏳ 03:10<00:41 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:05<00:00 |  5.98s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:05<00:00 |  5.98s/it

running experiment evaluations |████████▎ | 83/100 (83.0%) | ⏳ 03:16<00:59 |  3.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

running experiment evaluations |████████▍ | 84/100 (84.0%) | ⏳ 03:18<00:48 |  3.03s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.26s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.26s/it

running experiment evaluations |████████▌ | 85/100 (85.0%) | ⏳ 03:20<00:38 |  2.58s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

running experiment evaluations |████████▌ | 86/100 (86.0%) | ⏳ 03:22<00:34 |  2.44s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.26s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.26s/it

running experiment evaluations |████████▋ | 87/100 (87.0%) | ⏳ 03:23<00:28 |  2.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

running experiment evaluations |████████▊ | 88/100 (88.0%) | ⏳ 03:25<00:25 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.63s/it

running experiment evaluations |████████▉ | 89/100 (89.0%) | ⏳ 03:27<00:22 |  2.07s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

running experiment evaluations |█████████ | 90/100 (90.0%) | ⏳ 03:29<00:20 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.30s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.31s/it

running experiment evaluations |█████████ | 91/100 (91.0%) | ⏳ 03:31<00:17 |  1.93s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.05s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.05s/it

running experiment evaluations |█████████▏| 92/100 (92.0%) | ⏳ 03:33<00:16 |  2.05s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

running experiment evaluations |█████████▎| 93/100 (93.0%) | ⏳ 03:35<00:14 |  2.05s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.41s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.41s/it

running experiment evaluations |█████████▍| 94/100 (94.0%) | ⏳ 03:37<00:11 |  1.94s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

running experiment evaluations |█████████▌| 95/100 (95.0%) | ⏳ 03:39<00:09 |  1.95s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.35s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.35s/it

running experiment evaluations |█████████▌| 96/100 (96.0%) | ⏳ 03:41<00:07 |  1.85s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.60s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.60s/it

running experiment evaluations |█████████▋| 97/100 (97.0%) | ⏳ 03:46<00:08 |  2.75s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.21s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.21s/it

running experiment evaluations |█████████▊| 98/100 (98.0%) | ⏳ 03:48<00:05 |  2.67s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

running experiment evaluations |█████████▉| 99/100 (99.0%) | ⏳ 03:50<00:02 |  2.42s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.55s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.55s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 03:52<00:00 |  2.24s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 03:52<00:00 |  2.32s/it

  arize.experiments.functions | INFO | ✅ All evaluators completed.

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

skill-v2 mean score: 0.250

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

  arize.experiments.functions | INFO | 🧪 Experiment started.

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running tasks |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

running tasks |          | 1/100 (1.0%) | ⏳ 00:01<01:45 |  1.06s/it

running tasks |▏         | 2/100 (2.0%) | ⏳ 00:01<01:29 |  1.10it/s

running tasks |▎         | 3/100 (3.0%) | ⏳ 00:02<01:35 |  1.02it/s

running tasks |▍         | 4/100 (4.0%) | ⏳ 00:03<01:36 |  1.00s/it

running tasks |▌         | 5/100 (5.0%) | ⏳ 00:05<01:43 |  1.08s/it

running tasks |▌         | 6/100 (6.0%) | ⏳ 00:06<01:38 |  1.05s/it

running tasks |▋         | 7/100 (7.0%) | ⏳ 00:07<01:36 |  1.04s/it

running tasks |▊         | 8/100 (8.0%) | ⏳ 00:08<01:35 |  1.04s/it

running tasks |▉         | 9/100 (9.0%) | ⏳ 00:09<01:32 |  1.02s/it

running tasks |█         | 10/100 (10.0%) | ⏳ 00:10<01:33 |  1.03s/it

running tasks |█         | 11/100 (11.0%) | ⏳ 00:12<02:11 |  1.48s/it

running tasks |█▏        | 12/100 (12.0%) | ⏳ 00:13<01:59 |  1.36s/it

running tasks |█▎        | 13/100 (13.0%) | ⏳ 00:14<01:48 |  1.25s/it

running tasks |█▍        | 14/100 (14.0%) | ⏳ 00:16<01:45 |  1.23s/it

running tasks |█▌        | 15/100 (15.0%) | ⏳ 00:17<02:01 |  1.43s/it

running tasks |█▌        | 16/100 (16.0%) | ⏳ 00:19<02:03 |  1.47s/it

running tasks |█▋        | 17/100 (17.0%) | ⏳ 00:20<01:48 |  1.31s/it

running tasks |█▊        | 18/100 (18.0%) | ⏳ 00:21<01:43 |  1.26s/it

running tasks |█▉        | 19/100 (19.0%) | ⏳ 00:22<01:34 |  1.16s/it

running tasks |██        | 20/100 (20.0%) | ⏳ 00:23<01:28 |  1.10s/it

running tasks |██        | 21/100 (21.0%) | ⏳ 00:24<01:29 |  1.13s/it

running tasks |██▏       | 22/100 (22.0%) | ⏳ 00:25<01:33 |  1.19s/it

running tasks |██▎       | 23/100 (23.0%) | ⏳ 00:26<01:25 |  1.11s/it

running tasks |██▍       | 24/100 (24.0%) | ⏳ 00:27<01:24 |  1.11s/it

running tasks |██▌       | 25/100 (25.0%) | ⏳ 00:28<01:19 |  1.06s/it

running tasks |██▌       | 26/100 (26.0%) | ⏳ 00:29<01:15 |  1.02s/it

running tasks |██▋       | 27/100 (27.0%) | ⏳ 00:31<01:17 |  1.06s/it

running tasks |██▊       | 28/100 (28.0%) | ⏳ 00:32<01:16 |  1.06s/it

running tasks |██▉       | 29/100 (29.0%) | ⏳ 00:33<01:19 |  1.12s/it

running tasks |███       | 30/100 (30.0%) | ⏳ 00:34<01:17 |  1.11s/it

running tasks |███       | 31/100 (31.0%) | ⏳ 00:35<01:19 |  1.15s/it

running tasks |███▏      | 32/100 (32.0%) | ⏳ 00:37<01:24 |  1.24s/it

running tasks |███▎      | 33/100 (33.0%) | ⏳ 00:38<01:16 |  1.14s/it

running tasks |███▍      | 34/100 (34.0%) | ⏳ 00:39<01:13 |  1.11s/it

running tasks |███▌      | 35/100 (35.0%) | ⏳ 00:39<01:07 |  1.05s/it

running tasks |███▌      | 36/100 (36.0%) | ⏳ 00:41<01:10 |  1.10s/it

running tasks |███▋      | 37/100 (37.0%) | ⏳ 00:42<01:08 |  1.09s/it

running tasks |███▊      | 38/100 (38.0%) | ⏳ 00:43<01:04 |  1.04s/it

running tasks |███▉      | 39/100 (39.0%) | ⏳ 00:44<01:05 |  1.08s/it

running tasks |████      | 40/100 (40.0%) | ⏳ 00:45<01:05 |  1.10s/it

running tasks |████      | 41/100 (41.0%) | ⏳ 00:46<01:07 |  1.15s/it

running tasks |████▏     | 42/100 (42.0%) | ⏳ 00:48<01:10 |  1.21s/it

running tasks |████▎     | 43/100 (43.0%) | ⏳ 00:49<01:09 |  1.22s/it

running tasks |████▍     | 44/100 (44.0%) | ⏳ 00:50<01:07 |  1.21s/it

running tasks |████▌     | 45/100 (45.0%) | ⏳ 00:51<01:04 |  1.16s/it

running tasks |████▌     | 46/100 (46.0%) | ⏳ 00:52<01:00 |  1.13s/it

running tasks |████▋     | 47/100 (47.0%) | ⏳ 00:53<00:57 |  1.09s/it

running tasks |████▊     | 48/100 (48.0%) | ⏳ 00:55<01:00 |  1.17s/it

running tasks |████▉     | 49/100 (49.0%) | ⏳ 00:56<00:57 |  1.13s/it

running tasks |█████     | 50/100 (50.0%) | ⏳ 00:57<00:57 |  1.15s/it

running tasks |█████     | 51/100 (51.0%) | ⏳ 00:58<00:53 |  1.09s/it

running tasks |█████▏    | 52/100 (52.0%) | ⏳ 00:59<00:52 |  1.10s/it

running tasks |█████▎    | 53/100 (53.0%) | ⏳ 01:00<00:49 |  1.06s/it

running tasks |█████▍    | 54/100 (54.0%) | ⏳ 01:01<00:48 |  1.06s/it

running tasks |█████▌    | 55/100 (55.0%) | ⏳ 01:02<00:51 |  1.13s/it

running tasks |█████▌    | 56/100 (56.0%) | ⏳ 01:03<00:47 |  1.09s/it

running tasks |█████▋    | 57/100 (57.0%) | ⏳ 01:05<00:53 |  1.23s/it

running tasks |█████▊    | 58/100 (58.0%) | ⏳ 01:06<00:50 |  1.20s/it

running tasks |█████▉    | 59/100 (59.0%) | ⏳ 01:08<00:58 |  1.43s/it

running tasks |██████    | 60/100 (60.0%) | ⏳ 01:09<00:52 |  1.32s/it

running tasks |██████    | 61/100 (61.0%) | ⏳ 01:10<00:50 |  1.29s/it

running tasks |██████▏   | 62/100 (62.0%) | ⏳ 01:11<00:48 |  1.28s/it

running tasks |██████▎   | 63/100 (63.0%) | ⏳ 01:12<00:43 |  1.18s/it

running tasks |██████▍   | 64/100 (64.0%) | ⏳ 01:13<00:41 |  1.16s/it

running tasks |██████▌   | 65/100 (65.0%) | ⏳ 01:14<00:37 |  1.08s/it

running tasks |██████▌   | 66/100 (66.0%) | ⏳ 01:15<00:34 |  1.02s/it

running tasks |██████▋   | 67/100 (67.0%) | ⏳ 01:17<00:40 |  1.24s/it

running tasks |██████▊   | 68/100 (68.0%) | ⏳ 01:18<00:37 |  1.16s/it

running tasks |██████▉   | 69/100 (69.0%) | ⏳ 01:19<00:33 |  1.08s/it

running tasks |███████   | 70/100 (70.0%) | ⏳ 01:20<00:31 |  1.04s/it

running tasks |███████   | 71/100 (71.0%) | ⏳ 01:21<00:29 |  1.02s/it

running tasks |███████▏  | 72/100 (72.0%) | ⏳ 01:22<00:27 |  1.00it/s

running tasks |███████▎  | 73/100 (73.0%) | ⏳ 01:23<00:27 |  1.01s/it

running tasks |███████▍  | 74/100 (74.0%) | ⏳ 01:24<00:26 |  1.03s/it

running tasks |███████▌  | 75/100 (75.0%) | ⏳ 01:25<00:26 |  1.04s/it

running tasks |███████▌  | 76/100 (76.0%) | ⏳ 01:26<00:24 |  1.00s/it

running tasks |███████▋  | 77/100 (77.0%) | ⏳ 01:27<00:24 |  1.08s/it

running tasks |███████▊  | 78/100 (78.0%) | ⏳ 01:28<00:23 |  1.08s/it

running tasks |███████▉  | 79/100 (79.0%) | ⏳ 01:29<00:20 |  1.01it/s

running tasks |████████  | 80/100 (80.0%) | ⏳ 01:30<00:23 |  1.15s/it

running tasks |████████  | 81/100 (81.0%) | ⏳ 01:32<00:22 |  1.18s/it

running tasks |████████▏ | 82/100 (82.0%) | ⏳ 01:33<00:20 |  1.12s/it

running tasks |████████▎ | 83/100 (83.0%) | ⏳ 01:33<00:17 |  1.03s/it

running tasks |████████▍ | 84/100 (84.0%) | ⏳ 01:34<00:16 |  1.03s/it

running tasks |████████▌ | 85/100 (85.0%) | ⏳ 01:35<00:15 |  1.01s/it

running tasks |████████▌ | 86/100 (86.0%) | ⏳ 01:36<00:14 |  1.02s/it

running tasks |████████▋ | 87/100 (87.0%) | ⏳ 01:37<00:12 |  1.02it/s

running tasks |████████▊ | 88/100 (88.0%) | ⏳ 01:38<00:11 |  1.01it/s

running tasks |████████▉ | 89/100 (89.0%) | ⏳ 01:39<00:11 |  1.02s/it

running tasks |█████████ | 90/100 (90.0%) | ⏳ 01:40<00:10 |  1.01s/it

running tasks |█████████ | 91/100 (91.0%) | ⏳ 01:41<00:08 |  1.02it/s

running tasks |█████████▏| 92/100 (92.0%) | ⏳ 01:42<00:07 |  1.05it/s

running tasks |█████████▎| 93/100 (93.0%) | ⏳ 01:43<00:06 |  1.01it/s

running tasks |█████████▍| 94/100 (94.0%) | ⏳ 01:44<00:05 |  1.03it/s

running tasks |█████████▌| 95/100 (95.0%) | ⏳ 01:45<00:04 |  1.01it/s

running tasks |█████████▌| 96/100 (96.0%) | ⏳ 01:46<00:03 |  1.02it/s

running tasks |█████████▋| 97/100 (97.0%) | ⏳ 01:47<00:03 |  1.01s/it

running tasks |█████████▊| 98/100 (98.0%) | ⏳ 01:48<00:02 |  1.01s/it

running tasks |█████████▉| 99/100 (99.0%) | ⏳ 01:49<00:00 |  1.01it/s

running tasks |██████████| 100/100 (100.0%) | ⏳ 01:50<00:00 |  1.01s/it

running tasks |██████████| 100/100 (100.0%) | ⏳ 01:50<00:00 |  1.11s/it

  arize.experiments.functions | INFO | ✅ Task runs completed.
Tasks Summary (07/03/26 11:21 AM +0900)
---------------------------------------
   n_examples  n_runs  n_errors
0         100     100         0

  arize.experiments.evaluators.executors | WARNING | 🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

running experiment evaluations |          | 0/100 (0.0%) | ⏳ 00:00<? | ?it/s

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

running experiment evaluations |          | 1/100 (1.0%) | ⏳ 00:02<03:24 |  2.06s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.36s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.36s/it

running experiment evaluations |▏         | 2/100 (2.0%) | ⏳ 00:03<02:57 |  1.81s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.41s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.41s/it

running experiment evaluations |▎         | 3/100 (3.0%) | ⏳ 00:06<03:33 |  2.20s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.85s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.85s/it

running experiment evaluations |▍         | 4/100 (4.0%) | ⏳ 00:08<03:28 |  2.17s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.33s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.33s/it

running experiment evaluations |▌         | 5/100 (5.0%) | ⏳ 00:10<03:06 |  1.96s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

running experiment evaluations |▌         | 6/100 (6.0%) | ⏳ 00:12<03:21 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:09<00:00 |  9.21s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:09<00:00 |  9.21s/it

running experiment evaluations |▋         | 7/100 (7.0%) | ⏳ 00:22<07:02 |  4.54s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.80s/it

running experiment evaluations |▊         | 8/100 (8.0%) | ⏳ 00:24<05:45 |  3.75s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.81s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.81s/it

running experiment evaluations |▉         | 9/100 (9.0%) | ⏳ 00:26<04:53 |  3.23s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

running experiment evaluations |█         | 10/100 (10.0%) | ⏳ 00:27<04:10 |  2.78s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.51s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.52s/it

running experiment evaluations |█         | 11/100 (11.0%) | ⏳ 00:29<03:40 |  2.48s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.62s/it

running experiment evaluations |█▏        | 12/100 (12.0%) | ⏳ 00:31<03:22 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.46s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.46s/it

running experiment evaluations |█▎        | 13/100 (13.0%) | ⏳ 00:33<03:04 |  2.12s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.86s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.87s/it

running experiment evaluations |█▍        | 14/100 (14.0%) | ⏳ 00:36<03:28 |  2.43s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.83s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.83s/it

running experiment evaluations |█▌        | 15/100 (15.0%) | ⏳ 00:38<03:17 |  2.33s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

running experiment evaluations |█▌        | 16/100 (16.0%) | ⏳ 00:40<03:11 |  2.28s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.45s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.46s/it

running experiment evaluations |█▋        | 17/100 (17.0%) | ⏳ 00:42<02:55 |  2.11s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.47s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.47s/it

running experiment evaluations |█▊        | 18/100 (18.0%) | ⏳ 00:45<03:08 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.44s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.44s/it

running experiment evaluations |█▉        | 19/100 (19.0%) | ⏳ 00:47<02:54 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.75s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.75s/it

running experiment evaluations |██        | 20/100 (20.0%) | ⏳ 00:51<03:36 |  2.71s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.34s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.34s/it

running experiment evaluations |██        | 21/100 (21.0%) | ⏳ 00:53<03:31 |  2.68s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.21s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.21s/it

running experiment evaluations |██▏       | 22/100 (22.0%) | ⏳ 00:56<03:24 |  2.62s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.05s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:04<00:00 |  4.05s/it

running experiment evaluations |██▎       | 23/100 (23.0%) | ⏳ 01:00<04:00 |  3.13s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.57s/it

running experiment evaluations |██▍       | 24/100 (24.0%) | ⏳ 01:02<03:28 |  2.74s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.49s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.50s/it

running experiment evaluations |██▌       | 25/100 (25.0%) | ⏳ 01:04<03:03 |  2.45s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.82s/it

running experiment evaluations |██▌       | 26/100 (26.0%) | ⏳ 01:06<02:53 |  2.34s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.53s/it

running experiment evaluations |██▋       | 27/100 (27.0%) | ⏳ 01:07<02:38 |  2.17s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.40s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.41s/it

running experiment evaluations |██▊       | 28/100 (28.0%) | ⏳ 01:09<02:25 |  2.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

running experiment evaluations |██▉       | 29/100 (29.0%) | ⏳ 01:11<02:22 |  2.00s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

running experiment evaluations |███       | 30/100 (30.0%) | ⏳ 01:13<02:16 |  1.95s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.90s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.91s/it

running experiment evaluations |███       | 31/100 (31.0%) | ⏳ 01:16<02:39 |  2.32s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.88s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.88s/it

running experiment evaluations |███▏      | 32/100 (32.0%) | ⏳ 01:19<02:54 |  2.56s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.69s/it

running experiment evaluations |███▎      | 33/100 (33.0%) | ⏳ 01:21<02:39 |  2.38s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.81s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.81s/it

running experiment evaluations |███▍      | 34/100 (34.0%) | ⏳ 01:24<02:50 |  2.59s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

running experiment evaluations |███▌      | 35/100 (35.0%) | ⏳ 01:26<02:33 |  2.37s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.87s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.87s/it

running experiment evaluations |███▌      | 36/100 (36.0%) | ⏳ 01:28<02:27 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

running experiment evaluations |███▋      | 37/100 (37.0%) | ⏳ 01:30<02:12 |  2.10s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.27s/it

running experiment evaluations |███▊      | 38/100 (38.0%) | ⏳ 01:32<02:18 |  2.23s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

running experiment evaluations |███▉      | 39/100 (39.0%) | ⏳ 01:34<02:09 |  2.12s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.17s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:03<00:00 |  3.18s/it

running experiment evaluations |████      | 40/100 (40.0%) | ⏳ 01:38<02:30 |  2.51s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

running experiment evaluations |████      | 41/100 (41.0%) | ⏳ 01:40<02:16 |  2.32s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.49s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.50s/it

running experiment evaluations |████▏     | 42/100 (42.0%) | ⏳ 01:41<02:04 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.86s/it

running experiment evaluations |████▎     | 43/100 (43.0%) | ⏳ 01:43<02:02 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.64s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.64s/it

running experiment evaluations |████▍     | 44/100 (44.0%) | ⏳ 01:45<01:56 |  2.07s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.51s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.51s/it

running experiment evaluations |████▌     | 45/100 (45.0%) | ⏳ 01:47<01:49 |  1.98s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.92s/it

running experiment evaluations |████▌     | 46/100 (46.0%) | ⏳ 01:49<01:50 |  2.04s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

running experiment evaluations |████▋     | 47/100 (47.0%) | ⏳ 01:52<01:54 |  2.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.42s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.42s/it

running experiment evaluations |████▊     | 48/100 (48.0%) | ⏳ 01:53<01:44 |  2.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

running experiment evaluations |████▉     | 49/100 (49.0%) | ⏳ 01:55<01:41 |  2.00s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

running experiment evaluations |█████     | 50/100 (50.0%) | ⏳ 01:57<01:41 |  2.03s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.40s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.40s/it

running experiment evaluations |█████     | 51/100 (51.0%) | ⏳ 01:59<01:34 |  1.92s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

running experiment evaluations |█████▏    | 52/100 (52.0%) | ⏳ 02:01<01:32 |  1.94s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.84s/it

running experiment evaluations |█████▎    | 53/100 (53.0%) | ⏳ 02:03<01:33 |  1.99s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.68s/it

running experiment evaluations |█████▍    | 54/100 (54.0%) | ⏳ 02:05<01:30 |  1.98s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.16s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.16s/it

running experiment evaluations |█████▌    | 55/100 (55.0%) | ⏳ 02:08<01:34 |  2.11s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.17s/it

running experiment evaluations |█████▌    | 56/100 (56.0%) | ⏳ 02:10<01:37 |  2.21s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.90s/it

running experiment evaluations |█████▋    | 57/100 (57.0%) | ⏳ 02:12<01:34 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.58s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.59s/it

running experiment evaluations |█████▊    | 58/100 (58.0%) | ⏳ 02:14<01:27 |  2.09s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.35s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.35s/it

running experiment evaluations |█████▉    | 59/100 (59.0%) | ⏳ 02:16<01:19 |  1.95s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.72s/it

running experiment evaluations |██████    | 60/100 (60.0%) | ⏳ 02:18<01:18 |  1.97s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.05s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.05s/it

running experiment evaluations |██████    | 61/100 (61.0%) | ⏳ 02:20<01:20 |  2.07s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.11s/it

running experiment evaluations |██████▏   | 62/100 (62.0%) | ⏳ 02:22<01:22 |  2.16s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

running experiment evaluations |██████▎   | 63/100 (63.0%) | ⏳ 02:25<01:23 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.01s/it

running experiment evaluations |██████▍   | 64/100 (64.0%) | ⏳ 02:27<01:21 |  2.26s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

running experiment evaluations |██████▌   | 65/100 (65.0%) | ⏳ 02:29<01:18 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.39s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.39s/it

running experiment evaluations |██████▌   | 66/100 (66.0%) | ⏳ 02:31<01:10 |  2.07s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.61s/it

running experiment evaluations |██████▋   | 67/100 (67.0%) | ⏳ 02:33<01:06 |  2.01s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.22s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.23s/it

running experiment evaluations |██████▊   | 68/100 (68.0%) | ⏳ 02:35<01:08 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.58s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.58s/it

running experiment evaluations |██████▉   | 69/100 (69.0%) | ⏳ 02:38<01:13 |  2.36s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.37s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.37s/it

running experiment evaluations |███████   | 70/100 (70.0%) | ⏳ 02:40<01:04 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.43s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.43s/it

running experiment evaluations |███████   | 71/100 (71.0%) | ⏳ 02:42<01:06 |  2.31s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.35s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.36s/it

running experiment evaluations |███████▏  | 72/100 (72.0%) | ⏳ 02:44<00:58 |  2.10s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.05s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

running experiment evaluations |███████▎  | 73/100 (73.0%) | ⏳ 02:46<00:58 |  2.17s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.43s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.43s/it

running experiment evaluations |███████▍  | 74/100 (74.0%) | ⏳ 02:48<00:52 |  2.03s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.70s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.71s/it

running experiment evaluations |███████▌  | 75/100 (75.0%) | ⏳ 02:50<00:50 |  2.01s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.66s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.67s/it

running experiment evaluations |███████▌  | 76/100 (76.0%) | ⏳ 02:52<00:47 |  1.99s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.61s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.61s/it

running experiment evaluations |███████▋  | 77/100 (77.0%) | ⏳ 02:55<00:51 |  2.25s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.60s/it

running experiment evaluations |███████▊  | 78/100 (78.0%) | ⏳ 02:57<00:47 |  2.14s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.31s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.31s/it

running experiment evaluations |███████▉  | 79/100 (79.0%) | ⏳ 02:58<00:41 |  1.97s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.46s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.46s/it

running experiment evaluations |████████  | 80/100 (80.0%) | ⏳ 03:01<00:43 |  2.19s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.78s/it

running experiment evaluations |████████  | 81/100 (81.0%) | ⏳ 03:03<00:40 |  2.15s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.63s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.64s/it

running experiment evaluations |████████▏ | 82/100 (82.0%) | ⏳ 03:05<00:37 |  2.07s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.65s/it

running experiment evaluations |████████▎ | 83/100 (83.0%) | ⏳ 03:07<00:34 |  2.02s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.09s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.10s/it

running experiment evaluations |████████▍ | 84/100 (84.0%) | ⏳ 03:09<00:33 |  2.12s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.49s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.49s/it

running experiment evaluations |████████▌ | 85/100 (85.0%) | ⏳ 03:11<00:30 |  2.01s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.56s/it

running experiment evaluations |████████▌ | 86/100 (86.0%) | ⏳ 03:13<00:27 |  1.96s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.38s/it

running experiment evaluations |████████▋ | 87/100 (87.0%) | ⏳ 03:14<00:24 |  1.86s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.09s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.09s/it

running experiment evaluations |████████▊ | 88/100 (88.0%) | ⏳ 03:17<00:24 |  2.01s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.06s/it

running experiment evaluations |████████▉ | 89/100 (89.0%) | ⏳ 03:19<00:23 |  2.10s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.50s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.50s/it

running experiment evaluations |█████████ | 90/100 (90.0%) | ⏳ 03:22<00:23 |  2.30s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.18s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.19s/it

running experiment evaluations |█████████ | 91/100 (91.0%) | ⏳ 03:24<00:21 |  2.35s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.20s/it

running experiment evaluations |█████████▏| 92/100 (92.0%) | ⏳ 03:27<00:19 |  2.38s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.77s/it

running experiment evaluations |█████████▎| 93/100 (93.0%) | ⏳ 03:29<00:15 |  2.28s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.57s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.58s/it

running experiment evaluations |█████████▍| 94/100 (94.0%) | ⏳ 03:32<00:14 |  2.45s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.64s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.64s/it

running experiment evaluations |█████████▌| 95/100 (95.0%) | ⏳ 03:35<00:12 |  2.58s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.57s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.57s/it

running experiment evaluations |█████████▌| 96/100 (96.0%) | ⏳ 03:37<00:10 |  2.66s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.88s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.88s/it

running experiment evaluations |█████████▋| 97/100 (97.0%) | ⏳ 03:40<00:07 |  2.50s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.89s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.89s/it

running experiment evaluations |█████████▊| 98/100 (98.0%) | ⏳ 03:42<00:04 |  2.40s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.24s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:02<00:00 |  2.25s/it

running experiment evaluations |█████████▉| 99/100 (99.0%) | ⏳ 03:44<00:02 |  2.43s/it

🐌!! If running inside a notebook, patching the event loop with nest_asyncio will allow asynchronous eval submission, and is significantly faster. To patch the event loop, run `nest_asyncio.apply()`.

llm_classify |          | 0/1 (0.0%) | ⏳ 00:00<? | ?it/s

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

llm_classify |██████████| 1/1 (100.0%) | ⏳ 00:01<00:00 |  1.95s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 03:46<00:00 |  2.36s/it

running experiment evaluations |██████████| 100/100 (100.0%) | ⏳ 03:46<00:00 |  2.27s/it

  arize.experiments.functions | INFO | ✅ All evaluators completed.

/Users/sean/projects/healingpaper/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.arize.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

skill-v3 mean score: 0.250

    version  score
0  skill-v0   0.22
1  skill-v1   0.23
2  skill-v2   0.25
3  skill-v3   0.25

In [15]:
hist_df = pd.DataFrame(history)
best = hist_df.loc[hist_df["score"].idxmax()]
print(hist_df.to_string(index=False))
print(f"\nBaseline (skill-v0): {history[0]['score']:.3f}")
print(f"Best: {best['version']} @ {best['score']:.3f}")

# Restore-best: leave SKILL.md at whichever version scored highest, not wherever the loop's
# last apply_skill happened to land. Every "skill-v{k}" score corresponds exactly to
# versions/v{k}.md (v0..v{N_ITERATIONS-1} archived by the loop above, v{N_ITERATIONS} archived
# by the snapshot_skill(N_ITERATIONS) call just added). Without this, re-running this notebook
# would silently measure the previous run's leftover last-iteration text as the new baseline.
best_idx = int(best["version"].replace("skill-v", ""))
apply_skill(open(f"{VERSIONS_DIR}/v{best_idx}.md").read())
print(f"\nSKILL.md restored to best version ({best['version']}).")
print("Compare experiments skill-v0..skill-v{} in the Arize UI.".format(N_ITERATIONS))

 version  score
skill-v0   0.22
skill-v1   0.23
skill-v2   0.25
skill-v3   0.25

Baseline (skill-v0): 0.220
Best: skill-v2 @ 0.250

SKILL.md restored to best version (skill-v2).
Compare experiments skill-v0..skill-v3 in the Arize UI.